export const russisch = [
	[ "(ab-, auf)runden\nRunde die Zahlen ab.","округлять – округлить\nЧисла округли","" ],
	[ "(an)dünsten, schmoren, dämpfen","потушать - потушить","" ],
	[ "(An-, Bleistift-)Spitzer","точилка","" ],
	[ "(be)fürchten\nbangen um","опасаться чего несов.\nопасаться за кого","" ],
	[ "(be)spritzen, beträufeln","сбрызгать - сбрызнуть","" ],
	[ "(den Zug) verpassen","отставать – остать (от поезда)","" ],
	[ "(Feder)Mäppchen","пенал","" ],
	[ "(Finger)Handschuhe","перчатки","" ],
	[ "(Foto) teilen (Handy), teilhaben lassen an","делиться чем (фото)","" ],
	[ "(für) nächste Woche (erwartet man ...)","на следующей неделе ждут ...","" ],
	[ "(Heft)Pflaster","лейкопластырь","" ],
	[ "(ich bekomme) von Ihnen … Rubel","C Bac шестьсот рублей","" ],
	[ "(jährliches) Gesundheitsfürsorgesystem","диспансеризация","" ],
	[ "(Kleider)Größe, Nummer","размер\nА есть на размер меньше?","" ],
	[ "(leicht) bewölkt","малооблачный","" ],
	[ "(sich etwas) dazuverdienen, nebenbei arbeiten","подрабатывать нес.","" ],
	[ "(sich) lohnen\n","стоить","Es lohnt sich, wegen … dorthin zu fahren\nТуда стоит поехать ради " ],
	[ "(zu) 900 Rubel pro Liter","по 900 рублей за литр","" ],
	[ "Aal","угорь м / угря","" ],
	[ "abblitzen lassen ugs.","отшить кого","" ],
	[ "Abfahrt, Abreise","разъезд","" ],
	[ "abfällig","ехидный","" ],
	[ "abgekocht","кипячёный","" ],
	[ "abgelegene Region","отдалённый район","" ],
	[ "Abitur, Abschlussprüfung","ЕГЭ – единый государственный экзамен","" ],
	[ "ablehnen\n","отказываться – отказаться от чего\n","eine Tasse Tee lehne ich nicht ab\nот чашки чая я не откажусь" ],
	[ "Abnahme","съём (снятие)","" ],
	[ "absagen","отменять - отменить","" ],
	[ "Absatz\nSchuhe mit hohem Absatz","каблук\nтуфли / обувь на высоких каблуках","" ],
	[ "abschaffen, auflösen, beseitigen","упразднять - упразднить","" ],
	[ "Abschnitt, Ausschnitt, Passage","отрывок","" ],
	[ "absichtlich, bewusst","намеренный, умышленный, преднамеренный","" ],
	[ "absolvieren; zu Ende führen, abschließen, beendigen","оканчивать - окончить","" ],
	[ "abstammen von, herrühren von, kommen von","происходить – произойти от","" ],
	[ "Absurdität","абсурд","" ],
	[ "Abteilung","отдел","" ],
	[ "abwarten","пережидать - переждать","" ],
	[ "abwaschen","промывать - промыть","" ],
	[ "abweisend","недружелюбный","" ],
	[ "Abzählreim","считалочка","" ],
	[ "ach du meine Güte","ёлки-палки","" ],
	[ "acht Wochen vor Ostern","за восемь недель до Пасхи","" ],
	[ "Actionfilm","боевик","" ],
	[ "addieren","складывать - сложить","" ],
	[ "adelig","дворянский","" ],
	[ "Adjektiv","имя прилагательное","" ],
	[ "Adler","орёл","" ],
	[ "Adresse","адрес, адреса мн.","" ],
	[ "Adventskranz ","рождественский венок","" ],
	[ "Adverb\nAdverbialpartizip","наречие\nдеепричастие","" ],
	[ "Ahorn","клён","" ],
	[ "AIDS","СПИД – синдром приобретённого иммунодефицита","" ],
	[ "Alge, Wasserpflanze","водоросль ж., -ли","" ],
	[ "Allgemeinwissen","эрудиция","" ],
	[ "Alltags-, alltäglich, gebräuchlich\ndie Münzserie, die im Umlauf ist, besteht aus …","обиходный\nлинейка обиходных монет состоит из ....","" ],
	[ "Alltagssituation","повседневная ситуация","" ],
	[ "Alphabet (Kyrilliza)","азбука (кириллица)","" ],
	[ "als","в качестве чего","" ],
	[ "also","итак","" ],
	[ "Altweibersommer","бабье лето","" ],
	[ "am Montag / am Mittwoch / am Sonntag\nam Ostersonntag","в понедельник / в среду / в воскресенье\nв пасхальное воскресенье","" ],
	[ "am Morgen","утром","" ],
	[ "am nächsten Tag","на следующий день","" ],
	[ "am Schwarzen Meer","на Чёрном море","" ],
	[ "am Vorabend","накануне вечером","" ],
	[ "am Wochenende","в выходные","" ],
	[ "am Wochenende\n\nan diesem Wochenende\n\nam vergangenen Wochenende\nan Wochentagen\nan diesem Freitag","в выходные\nна выходных\nв эти выходные\nна этих выходных\nна прошлых выходных\nв будные дни\nв эту пятницу","" ],
	[ "an den Fingern einer Hand abzählen","пересчитать по пальцам одной руки","" ],
	[ "an den Kassen","в кассах","" ],
	[ "an der Ecke (des Manegeplatzes und der Twerskaja-Straße)","на углу (Манежной площади и Тверской улицы)","" ],
	[ "an der Wende der zwanziger und dreißiger Jahre des zwanzigsten Jahrhunderts","на рубеже двадцатых – тридцатых годов XX века","" ],
	[ "an der Wende vom 17. zum 18. Jh","на рубеже 17-го и 18-го веков","" ],
	[ "an heißen Tagen","в жаркие дни","" ],
	[ "an Ostern","на Пасху","" ],
	[ "anbieten, zur Verfügung stellen","предоставлять","" ],
	[ "Anbieter (Informatik), Provider","провайдер","" ],
	[ "andere Länder, andere Sitten","другие страны – другие обычаи","" ],
	[ "anfangen etwas zu tun\nMit dreißig habe ich angefangen, mehr auf meine Ernährung zu achten.","стать делать\nПосле тридцати стала больше следить за своим рационом.","" ],
	[ "angeben, prahlen, sich rühmen","хвастаться – похвастаться чем","" ],
	[ "angeberisch, großtuerisch, prahlerisch","хвастливый","" ],
	[ "Angst haben vor, sich fürchten vor","бояться чего - кого","" ],
	[ "Angsthase","трусишка","" ],
	[ "ängstlich","трусливый","" ],
	[ "anhalten, übernachten, unterkommen","останавливаться - остановиться","" ],
	[ "Anhaltspunkt, Referenz(wert)","точка отсчёта","" ],
	[ "Ankleidekabine","примерочная","" ],
	[ "ankreuzen (Kästchen)\nkreuze an","отмечать – отметить крестиком\nотметь крестиком","" ],
	[ "Ankündigung, Erklärung, Bekanntmachung, Aushang, Inserat, Anzeige","объявление","" ],
	[ "Ankunft, Kongress; Ab-, Ausfahrt","съезд\nсъезд с автострады","" ],
	[ "anmutig, elegant, grazil, apart","изящный","" ],
	[ "anprobieren, testen (Kleidung)","примерять – примерить что","" ],
	[ "Anrufbeantworter","автоответчик","" ],
	[ "Anspielung, Andeutung","намёк","" ],
	[ "Anspitzer, (Bleistift)Spitzer","точилка","" ],
	[ "anspruchsvoll","изощрённый","" ],
	[ "anstrengen","утомительный\nнапряжённый","" ],
	[ "Antarktis","Антарктида","" ],
	[ "Antike","Древний мир","" ],
	[ "Antonym","антоним","" ],
	[ "Antrag ausfüllen","заполнять – заполнить заявление","" ],
	[ "Anzug (Kleidung)","пиджак","" ],
	[ "Applikation (Computer)\nmobile App","приложение\nмобильное приложение","" ],
	[ "arbeitsam, arbeitender","работящий","" ],
	[ "Archäologe","археолог","" ],
	[ "Arktis\nArktisches Meer, Arktischer Ozean","Арктик\nСеверный Ледовитый океан","" ],
	[ "Art nouveau","ар-нуво","" ],
	[ "Arzneimittel, Medikament, Medizin","лекарство","" ],
	[ "Asche","гарь ж.\nзола, золы","" ],
	[ "Aschermittwoch","Пепельная среда","" ],
	[ "au Backe!","ёлки зелёные!","" ],
	[ "Aubergine","баклажан","" ],
	[ "Audio","аудиозапись","" ],
	[ "auf den Link klicken","нажимать – нажать на ссылку","" ],
	[ "auf einmal, in einem Zug\nIch kann einen ganzen Liter auf einmal trinken.","за раз\nЯ могу за раз выпить целый литр.","" ],
	[ "auf geht’s!","махнём!\nмахнуть сов. разг.","" ],
	[ "auf keinen Fall","ни за что","" ],
	[ "auf Zehenspitzen","на цыпочках","" ],
	[ "Aufgang","восход","" ],
	[ "aufgeklärt","просвещённый","" ],
	[ "aufgeweckt","смышлёный","" ],
	[ "Aufguss (Tee)","заварка","" ],
	[ "Auflaufform","форма для запекания","" ],
	[ "Aufnahme, Foto","съёмка","" ],
	[ "aufnahmefähig, rasche Auffassungsgabe","понятливый","" ],
	[ "aufs äußerste, über alle Maßen","донельзя","" ],
	[ "aufsteigende Reihenfolge","в порядке возрастания\nпо возрастанию","" ],
	[ "aufteilen","распределять - распределить","" ],
	[ "Aufteilung","деление","" ],
	[ "aus Berechnung","по расчёту","" ],
	[ "ausbrechen (Feuer, Krieg)","вспыхивать - всhыхнуть","" ],
	[ "ausdrucken","распечатывать - распечатать","" ],
	[ "Ausfahrt","въезд","" ],
	[ "Ausgangspunkt, Aufhänger, Beginn, Eröffnung","завязка","" ],
	[ "ausgezeichnet","отличный","" ],
	[ "ausmachen, betragen\nihre Länge beträgt 85 km\n\nDie längste Eisenbahnlinie der Welt von Moskau bis Wladiwostok beträgt mehr als 9.000 Kilometer und 146 Stunden","составлять\nв длину он (город) достигает 85 км\nсамый длинный железнодорожный путь в мире от Москвы до Владивостока состовляет более 9000 километров и 146 часов","" ],
	[ "Ausrede","о т г оворка","" ],
	[ "Aussage","высказывание","" ],
	[ "Ausschnitt (Kleidungsstück)","декольте","" ],
	[ "Aussterben","вымирание","" ],
	[ "aussterben","вымирать","" ],
	[ "auswendig lernen\nHöre, sprich nach und lerne auswendig","запоминать\nСлушай, повторяй и запоминай!","" ],
	[ "auszeichnen, belohnen, ehren","награждать","" ],
	[ "Auszeichnung (Preisverleihung)","награда","" ],
	[ "Backpapier","бумага для выпечки","" ],
	[ "Backpulver","разрыхлитель","" ],
	[ "Badehose","плавки","" ],
	[ "bakterientötend","бактерицидный","" ],
	[ "Bargeld","наличные деньги","" ],
	[ "Bärlauch","черемша","" ],
	[ "Basilikum\nlila Basilikum","базилик\nреган","" ],
	[ "beabsichtigen, vorhaben","собираться - собраться","" ],
	[ "beantragen (Visum)","оформлять – оформить (визу)","" ],
	[ "Becher\nPapierbecher\nPlastikbecher\nWaffelbecher","стаканчик\nбумажный\nпластмассовый\nвафельный","" ],
	[ "bedeuten","обозначать – обозначить\nЧто обозначает слово ....?","" ],
	[ "Bedeutungslosigkeit","незначительность","" ],
	[ "Beeren\nBlaubeere\nBrombeere\nErdbeere\nHeidelbeere, Schwarzbeere\nHimbeere\nrote Johannisbeere\nschwarze Johannisbeere\nMoltebeere\nMoosbeere\nPreiselbeere\nStachelbeere\nWalderdbeere","ягоды\nголубика\nежевика\nклубника\nчерника\nмалина\nкрасная смородина\nчёрная смородина\nморошка\nклюква\nбрусника\nкрыжовник\nземляника","" ],
	[ "Befreiung","избавление","" ],
	[ "befreundet sein\nsich anfreunden","дружить – подружить\nдружиться - подружиться","" ],
	[ "begabt, fähig","способный","" ],
	[ "begehen, durchführen","проводить – провести\nторжественно проводят день знаний в школах","" ],
	[ "begeistern, entzücken;\nbewundern\nsich begeistern für","восхищать – восхитить\n\nвосхищаться – восхититься чем","" ],
	[ "begeistert sein von","(быть) в восторге от кого-либо","" ],
	[ "beglaubigte Übersetzung","заверенный перевод","" ],
	[ "begründen\nvervollständige die Präpositionen und begründe deine Wahl","обосновывать – обосновать\nдополни предлоги и обоснуй их выбор","" ],
	[ "Begrüßung\nBegrüßungsritual","приветствие\nритуал приветствия","" ],
	[ "behüten, bewahren, vorbeugen, sich schützen vor (Erkältung)","предохранять – предохранить себя от чего-л.","" ],
	[ "bei Begrüßung und Abschied","при приветствии и прощании","" ],
	[ "bei jedem Wetter","при любую погоду","" ],
	[ "bei jedem Wetter\nbei warmem Wetter","при любую погоду\nв тёплую погоду","" ],
	[ "bei mittlerer Hitze","на среднем огне","" ],
	[ "Beilage","гарнир","" ],
	[ "beinhalten","включать в себя","" ],
	[ "beitreten, sich anmelden, sich verbinden\ntritt (doch) der Facebookgruppe bei","присоединяться – присоединиться\nприсоединяйся к группе в фейсбуке","" ],
	[ "bekannt, berühmt sein (für)\n[sich einer Sache rühmen]","слáвиться (чем)","" ],
	[ "bekannt, berühmt sein (für)\n[sich einer Sache rühmen]","слáвиться (чем)","" ],
	[ "belebt(e) (Substantive)","одушелённые (сущестьвительные)","" ],
	[ "belesen, bewandert","начитанный","" ],
	[ "bellen","гавкать","" ],
	[ "Beluga-Kaviar","чёрная икра","" ],
	[ "Bemühung","старание","" ],
	[ "benoten","ставить – поставить оценку","" ],
	[ "Berater","советник","" ],
	[ "bereuen, bedauern, jdm leid tun","жалеть - пожалеть","" ],
	[ "Bernstein","янтарь м., янтаря","" ],
	[ "Berufung","призвание","" ],
	[ "berühmt","известный","" ],
	[ "beschuldigen","винить - обвинить","" ],
	[ "Besteck","столовые приборы","" ],
	[ "bestehende / etablierte Ordnung","сложивший порядок","" ],
	[ "besuchen\nzu Besuch sein\nzu Besuch gehen\njdn kurz besuchen, bei jdm kurz vorbeischauen","навещать - навестить \nбыть в гостях\nходить – идти в гости\nзайти в гости к","" ],
	[ "betont","под ударением","" ],
	[ "Betonung\nHauptbetonung\nNebenbetonung\nwechselnde / springende Betonung","ударение\nглавное ударение\nпобочное ударение\nпрыгающее ударение","" ],
	[ "Betrachtung, Besinnlichkeit, Anschauung","созерцание","" ],
	[ "Betriebswirt","экономист","" ],
	[ "Beute, Fang;\nGewinnung, Förderung (Geol.)","добыча","" ],
	[ "Bewohner, Mieter","постоялец","" ],
	[ "bewundern","любоваться","" ],
	[ "bezaubernd","очаровательный","" ],
	[ "Bezug (für Kissen), Überzug; Etui","чехол, чехла","" ],
	[ "Bilanz ziehen","подводить итоги","" ],
	[ "Bildungseinrichtung","учебное заведение","" ],
	[ "billig","дёшево - дешевле","" ],
	[ "bis\nbis einer der Spieler als erster alle Zahlen abgedeckt hat","пока ... не\nпока одни из играющих не закроет первым все числа","" ],
	[ "bitten um","просить чего? (помощи)","" ],
	[ "bitter schmecken","горчить","" ],
	[ "bitterer Frost","лютый мороз","" ],
	[ "Blätterteig","слоёное тесто","" ],
	[ "Blaubeere","голубика","" ],
	[ "bleiben\nbleibe gesund\ngeistig fit bleiben","оставаться – остаться\nоставайся здоровым\nоставаться в прекрасной форме","" ],
	[ "blühen","цвести","" ],
	[ "Blume, Blüte\nBlumenladen, -geschäft","цветок (цветка)\nцветочный магазин","" ],
	[ "Boden wischen, putzen","мыть пол","" ],
	[ "Boden wischen, putzen","мыть пол","" ],
	[ "Bodenschätze","полезные ископаемые","" ],
	[ "Bohnenkraut","чабер","" ],
	[ "böse\nböse Hexe","злоядный\nзлоядная ведьма","" ],
	[ "böse, böswillig","злостный","" ],
	[ "Botschaft (Landesvertretung)\nBotschaft (Nachricht)","посольство\nпослание","" ],
	[ "Braten","жаркое, жаркого","" ],
	[ "Brauch, Sitte","обычай","" ],
	[ "brauchen, gebrauchen (können), nützlich / verwendbar sein","пригодиться\nэти слова могут тебе пригодиться","" ],
	[ "Brauerei","пивоваренный завод","" ],
	[ "Bräutigam","жених","" ],
	[ "brechen, zerbrechen, in Stücke gehen\nbrechen, brechend voll sein","ломить (ломлю, ломишь, ломят)\n\nломиться","" ],
	[ "breit","широко - шире","" ],
	[ "Bremse","тормоз \nмн. тормоза","" ],
	[ "Brennholz","дрова","" ],
	[ "Brennnessel","крапива","" ],
	[ "Brombeere","ежевика","" ],
	[ "Bruch (Math.)\nBruchnote","дробь ж., дроби\nдробная оценка","" ],
	[ "Bruder","брат - братья","" ],
	[ "Brunnen","колодец","" ],
	[ "buchen, reservieren (Karten, Tisch)","бронировать - забронировать","" ],
	[ "Buchmesse","книжная ярмарка","" ],
	[ "Buffet","шведский стол","" ],
	[ "Bühnenbildner","декоратор","" ],
	[ "Bund (Kräuter)","пучок","" ],
	[ "Bundesland","федеральная земля","" ],
	[ "bunt, scheckig, gefleckt","пёстрый","" ],
	[ "Burg","замок","" ],
	[ "Butterwoche","Масленица","" ],
	[ "Celsius","(градусов) по Цельсию","" ],
	[ "Chilischote","стручок свежего острого перца","" ],
	[ "chillen","чилить\nчилю, чилишь, чилим, чилят","" ],
	[ "choleretisch, die Gallenabsonderung anregend","желчегонный","" ],
	[ "Christbaum / Neujahrstannenbaum","новогодняя ёлка","" ],
	[ "christlich","христианский","" ],
	[ "da hast du aber was Dummes / Blödes angestellt","ну и наломал же ты дров","" ],
	[ "darstellende Kunst","изобразительное искусство","" ],
	[ "das alte Russland\nAltrussland","Русь ж., Руси\nДревняя Русь","" ],
	[ "das ist aber ein Wetter\nWetterschwankung, -umschwung","ну и погодка\nперепад погоды","" ],
	[ "das ist erst der Anfang","это ещё цветочки","" ],
	[ "das ist ja toll\nsie riechen toll","вот это здорово\nпахнут обалденно","" ],
	[ "das kann ich aus dem Effeff","это я знаю назубок","" ],
	[ "das stimmt","это верно","" ],
	[ "das Ziel verfehlen","промахиваться - промахнуться","" ],
	[ "das Ziel verfehlen","промахиваться - промахнуться","" ],
	[ "Dattel, Dattelbaum","финик","" ],
	[ "Daunenjacke","пуховик","" ],
	[ "davon hat man schon genug","надоело","" ],
	[ "Deklination","склонение","" ],
	[ "deklinieren","склонять - просклонять","" ],
	[ "Delikatesse, Leckerei, Leckerbissen, Schmankerl","лакомство","" ],
	[ "Demonstrativpronomen","указательное местоимение","" ],
	[ "den Sieg erringen über, triumphieren über","одерживать – одержать победу над кем-чем","" ],
	[ "Denken, Denkweise\ndie Freiheit des Denkens\ndas (Nach)Denken","мышление\nсвобода мышления\nразмышление","" ],
	[ "Denkmal","памятник","" ],
	[ "der fünflängste Fluss","это пятая по протяжённости река","" ],
	[ "der Verdienst","заработок","" ],
	[ "deutlich, klar","внятный","" ],
	[ "Dialekt","говор","" ],
	[ "die beliebtesten (Sportarten) sind","наибольшей популярностью пользуются (что)","" ],
	[ "die fehlenden (ausgelassenen) Wörter","пропушенные слова\n(пропускать – пропустить)","" ],
	[ "die ganze Nacht","всю ночь","" ],
	[ "die Legende besagt","легенда гласит","" ],
	[ "die Legende besagt","легенда гласит","" ],
	[ "die Qualifikation bestehen","пройти квалификацию","" ],
	[ "die Qualifikation bestehen","пройти квалификацию","" ],
	[ "dieses Jahr ist Irkutsk 360 Jahre alt geworden","в этом году Иркутску исполнилось 360 лет","" ],
	[ "digital","цифровой","" ],
	[ "Dill","укроп","" ],
	[ "Disziplin, Fach, Teilgebiet","дисциплина","" ],
	[ "Doktorand","аспирант","" ],
	[ "Domplatz","соборная площадь","" ],
	[ "Dorf","деревня, село","" ],
	[ "Dörrfisch","вобла","" ],
	[ "draußen","за окном\nна дворе\nна улице","" ],
	[ "draußen","на улице","" ],
	[ "drei Reihen mit je fünf Ziffern","три ряда по пять цифр","" ],
	[ "Dreikönigstag / Taufe des Herrn","Крешение Господне","" ],
	[ "Dressing","заправка","" ],
	[ "Druckbuchstabe","печатная буква","" ],
	[ "drücken\nbedrängen","прижимать - прижать","" ],
	[ "Drucker","принтер","" ],
	[ "du bist lustig / du machst wohl Witze","ну ты даёшь","" ],
	[ "du bist strohdumm","ты глупый как пень","" ],
	[ "du kommst mit dem nächsten Zug dorthin","ты доберёшься туда на попутном поезде","" ],
	[ "dumpf, gedämpft","приглушённый (звук)","" ],
	[ "düngen","удобрять - удобрить","" ],
	[ "Dünger","удобрение","" ],
	[ "dünn","тонко - тоньше","" ],
	[ "durchblättern","перелистывать - перелистать","" ],
	[ "Durchfall","понос","" ],
	[ "durchführen, stattfinden, durchgehen\neine Befragung durchführen\nStaatsempfänge stattfinden\n\nHier finden … statt\n\n\nDie Ballettpremiere fand am 3. Januar 1890 statt","проходить – пройти\n\nпроводить – провести опрос\nпроводить государственные приёмы\nЗдесь проходят популярный кинофестиваль и фестиваль джаза\nПремьера балета состоялась 3 января 1890","" ],
	[ "Durchgang-\nDurchgangsverkehr\nDurchwahl\nOmnibusbefragung","сквозной\nсквозной проезд\nсквозной набор\nсквозной опрос","" ],
	[ "echt? wirklich? tatsächlich?","да ладно!","" ],
	[ "Ehe","брак","" ],
	[ "Ehefrau\nEhemann","жена - жёны\nмуж - мужья","" ],
	[ "Ehre\nzu Ehren","честь ж., чести \nв честь кого-чего","" ],
	[ "ehrgeizig","честолюбивый","" ],
	[ "Eigelb\nEiweiß","желток\nбелок","" ],
	[ "Eigenheim, Einfamilienhaus, Villa","особняк","" ],
	[ "eigentlich\nAlina kommt eigentlich aus ... (ist geboren in ….) ","вообще\nАлина вообще родом из ","" ],
	[ "ein Arzeimittel / Medikament verschreiben gegen","выписать лекарство от+ род. п.\n\nВрач выписал мне лекарство от рвота","" ],
	[ "ein beweglicher Feiertag sein","не иметь календарного дня","" ],
	[ "ein Gesetz anwenden","применять – применить закон","" ],
	[ "ein Gesetz verabschieden","принимать – принять закон","" ],
	[ "ein halbes Glas","пол стакана","" ],
	[ "ein paar (einige)","парочка","" ],
	[ "eindeutig\nwo die Bedeutung nicht eindeutig ist","однозначный\nгде смысл может исказиться","" ],
	[ "eine Kur machen","полечиться","" ],
	[ "eine Woche vor der Fastenzeit","за неделю до начала Великого Поста","" ],
	[ "einen Tisch für zwei bestellen","заказать столик на двоих","" ],
	[ "einfach","просто - проще","" ],
	[ "einfach schrecklich","просто кошмар\nпросто завал","" ],
	[ "Einfahrt","въезд","" ],
	[ "einfallsreich","практичный","" ],
	[ "einheimisch; Einheimischer","местный","" ],
	[ "einig, freundlich","дружный","" ],
	[ "einigermaßen","ничего","" ],
	[ "Einkaufszentrum","торговый центр","" ],
	[ "Einreise","въезд","" ],
	[ "einschieben, einfügen, einsetzen","вставлять - вставить","" ],
	[ "einweichen, nass machen","замачивать - замочить","" ],
	[ "Einweihungsparty","новоселье","" ],
	[ "einzigartig","уникальный","" ],
	[ "Eisbahn","каток","" ],
	[ "eiskalt","холодный как лёд","" ],
	[ "Eiskunstlauf","фигурное катание","" ],
	[ "eitrig","гнойный","" ],
	[ "Elefant\nElefantenbaby","слон\nслонёнок","" ],
	[ "Element","стихия","" ],
	[ "Elfenbein","слоновая кость","" ],
	[ "Elster","сорока","" ],
	[ "Email, E-Mail\nE-Mail-Adresse","имейл\nадрес электронной почты","" ],
	[ "empfindlich","чувствительный","" ],
	[ "eng","узко - уже","" ],
	[ "Ente","утка","" ],
	[ "entlangfahren an","проезжать что","" ],
	[ "Entstehung","возникновение","" ],
	[ "Entwicklung der Fähigkeiten","рост мастерства","" ],
	[ "Entwicklung, Förderung, Erarbeitung","разработка (полезных ископаемых)","" ],
	[ "Entzündung","воспаление","" ],
	[ "Erbrechen","рвота","" ],
	[ "Erbse","горошек, -ка","" ],
	[ "Erdbeere","клубнинка","" ],
	[ "Erfindung","изобретение","" ],
	[ "Erfrierung","обморожение","" ],
	[ "Erfrischungsgetränk","прохладительный напиток","" ],
	[ "ergänzen, dazuschreiben","дописать\nдополнять - дополнить","" ],
	[ "Erholungs-, Kurort","город-курорт","" ],
	[ "erkennen","распознавать - распознать","" ],
	[ "Erntedankfest","праздник урожая","" ],
	[ "Ersatzspieler","запасной игрок","" ],
	[ "ersetzen durch","заменять - заменить на что","" ],
	[ "erstaunlich","поразительно","" ],
	[ "erstickende Hitze","духота","" ],
	[ "Ertrunkener","утопленник","" ],
	[ "erwähnenswert","стоить упомянуть","" ],
	[ "es blitzt","молния сверкает","" ],
	[ "es donnert","гром гремит","" ],
	[ "es hagelt\nes soll Hagel geben / es soll hageln / sie haben Hagel gemeldet","идёт град\nобещали град","" ],
	[ "es kratzt mir im Hals","у меня першит в горле","" ],
	[ "es lebe die Völkerverständigung","да здравствует взаимопонимание","" ],
	[ "es regnet in Strömen","дождь льёт как из ведра","" ],
	[ "Eskimo","эскимос !","" ],
	[ "essbar","съедобный","" ],
	[ "Essenszeit","время приёма пищи","" ],
	[ "Estland\nEste, Estin","Эстония\nэстнонец, эстонка","" ],
	[ "Estragon","тархун","" ],
	[ "etwas aus dem Effeff können","знать что-л. назубок","" ],
	[ "etwas besorgen, kaufen gehen","пойти за чем","" ],
	[ "etwas gegen Schmerzen","что-нибудь от боли","" ],
	[ "etwas gerne tun, sich gerne beschäftigen mit, schwärmen für","увлекаться чем (твор.)","" ],
	[ "etwas lässt zu wünschen übrig","что-то оставляет желать","" ],
	[ "etwas sehr gerne mögen, anbeten, schwärmen","обожать несов.","" ],
	[ "etwas verfolgen (a. fig.) (Ereignis)","следить за чем","" ],
	[ "Eule","сова","" ],
	[ "Euro","евро м. (unveränderlich) ","" ],
	[ "Facebook","Фейсбук","" ],
	[ "Fähigkeit","умение","" ],
	[ "Fähre","паром","" ],
	[ "Fahrtintervall","интервал движения","" ],
	[ "fallen auf, zusammenfallen mit;\n(her)ausfallen, herausgleiten;\nfallen (Niederschlag);\nzuteilwerden, zufallen","выпадать – выпасть на что\n\n\nкому","" ],
	[ "fälschlicherweise","по недоразумению","" ],
	[ "Falschmeldung, Ente","утка","" ],
	[ "Fan, leidenschaftlicher Anhänger, Bewunderer","болельщик\nпоклонник","" ],
	[ "Farbe\n\nWas hat welche Farbe?","цвет, цвета\nцвета (мн. ч.)\nЧто какого цвета?","" ],
	[ "Färben","покраска","" ],
	[ "färben, tönen, mit Farbe anstreichen","красить - покрасить","" ],
	[ "fast, beinahe, nahezu\ngilt für jeden Bildungsbürger als nahezu obligatorisch","едва не\nсчитается едва ли не обязательным для каждого просвещённого человека","" ],
	[ "fasten, die Fastenzeit befolgen","поститься (несов.) \nпощусь, постишься","" ],
	[ "Fastenzeit\nFastenrezept","(Большой) Пост\nпостный рецепт","" ],
	[ "Faulpelz","лентяй","" ],
	[ "Fäustlinge, Fausthandschuhe","варежки, варежек","" ],
	[ "federleicht","лёгкий как пёрышко","" ],
	[ "Federmappe","пенал","" ],
	[ "fegen, kehren","подметать - подмести","" ],
	[ "fehlerhaft, minderwertig","недоброкачественный","" ],
	[ "feiern, begehen ugs.","отмечать – отметить (Новый год)\nпраздновать – отпраздновать","" ],
	[ "Feigheit","трусость ж (-ти)","" ],
	[ "fein","мелкий, мельче","" ],
	[ "Fertigkeit","навык (практическое умение)","" ],
	[ "fertigschreiben, dazuschreiben","дописывать - дописать","" ],
	[ "fest","прочный","" ],
	[ "fester Teig","крутое тесто","" ],
	[ "Festland","суша","" ],
	[ "festlegen, feststellen","устанавливать – установить\nсистема устанавливающая зависимость различных свойств элементов от зарядаю","" ],
	[ "Festplatte","жёсткий диск","" ],
	[ "feststehende / idiomatische Redewendung","устойчивое выражение\nнастойчивый оборот\nоборот речи","" ],
	[ "Feuerwehr","пожарная команда\nпожарная охрана","" ],
	[ "Filmvorführung","кинопаказ","" ],
	[ "Filzstift","фломастер","" ],
	[ "Firmenlogo","логотип","" ],
	[ "Fischer","рыбак, рыбака","" ],
	[ "Fischsuppe","уха","" ],
	[ "flach (Gelände)\n(Wasser)\n(seicht fig.)","равнинный, низменный\nмелкий, неглубокий\nплоский","" ],
	[ "Fläche; Platz","площадь","" ],
	[ "flechten","плести – сплести\nплету, плетёшь, плетут\nзаплетать - заплести","" ],
	[ "Fleischwolf","мясорубка","" ],
	[ "fleißig, strebsam","усердный","" ],
	[ "Flieder","сирень ж. сирени","" ],
	[ "fliederfarben","сиреневый","" ],
	[ "fließend\nunter fließendem Wasser","проточный\nпод проточной водой","" ],
	[ "Flip-Flops (eigentlich: Latschen)","шлёпанцы","" ],
	[ "Flugticket","билет на самолёт","" ],
	[ "Fooddesigner","фуд-дизайнер","" ],
	[ "fördern, begünstigen, beitragen","способствовать – поспособствовать кому-чему\nРоссийский дом способствует изучению русского языка","" ],
	[ "Form beim Zählen","счётная форма","" ],
	[ "Fragebogen; Umfrage\nVisumsantrag","анкета\nвизовая анкета","" ],
	[ "Fragewort","воспросительное слово","" ],
	[ "freiwillig","добровольный","" ],
	[ "Freizeit\nin der Freizeit, in der freien Zeit","досуг\nв свободное время","" ],
	[ "Freund","друг - друзья","" ],
	[ "freundlich","приветливый","" ],
	[ "freundschaftlich, freundlich, nett","дружелюбный","" ],
	[ "Frikadellen","котлеты","" ],
	[ "fröhlich (Musik)","задорный","" ],
	[ "Fruchtfleisch","сердцевина","" ],
	[ "früh","рано - раньше","" ],
	[ "füllen","начинять - начинить","" ],
	[ "Füllung\nKuchen mit Füllung\nFüllung mit Karamell\nFüllung mit Beeren\nFüllung mit Honig\nFüllung mit Nüssen","начинка\nпирог с начинкой\nкарамельная начинка\nягодная начинка\nмедовая начинка\nореховая начинка","" ],
	[ "für (zwei Personen)","на две порции\nна 4 – 6 порций","" ],
	[ "für den üblichen Zweck","использование в стандартных целях","" ],
	[ "für eine Woche","на недельку","" ],
	[ "für einige Stunden","на несколько часов","" ],
	[ "Für welchen Anlass brauchen Sie einen Strauß?","Вам по какому поводу нужен букет?","" ],
	[ "Fürst\nFürstin","князь\nкняжна","" ],
	[ "Fußballnationalmannschaft","сборная","" ],
	[ "gackern","кудахтать","" ],
	[ "Galle, Gallenblase","желчный пузырь","" ],
	[ "gängig, verbreitet","распространённый","" ],
	[ "ganz, völlig, gründlich, ordentlich","основательно","" ],
	[ "Gartentor, -pforte","калитка","" ],
	[ "Gäste haben\nGäste einladen","у нас сегодня гости\nприглашать – пригласить гостей","" ],
	[ "gastfreundlich","гостеприимный","" ],
	[ "Gastfreundschaft, Gastfreundlichkeit","гостеприимство","" ],
	[ "Gastrolle, -spiel, -vorstellung\nauf Italienreise sein (und dort Vorstellungen geben)","гастроль ж., -ли\nнаходить на гастролях в Италии","" ],
	[ "Gauner, Dieb","жулик","" ],
	[ "Gebäck","печёное","" ],
	[ "gebürtig bin ich aus … \nich bin aus … \ngeboren bin ich in ….","я родом из ","" ],
	[ "geduldig","терпеливый","" ],
	[ "geeignet, angebracht, passend","уместный","" ],
	[ "Gefäß","сосуд","" ],
	[ "Gehacktes, Hackfleisch","фарш (мясной)","" ],
	[ "Gehalt, Lohn","оклад\nзарплата","" ],
	[ "gehäufter Esslöffel","столовая ложка с горкой","" ],
	[ "geheim","тайный","" ],
	[ "Geheimnis","тайна\nсекрет","" ],
	[ "gehen zu, sich begeben zu","отправляться – отправиться в","" ],
	[ "gehören zu","входить в\nБайкал входит с 1986 года в список Всемирного природного наследия ЮНЕСКО","" ],
	[ "Geizhals","скупердяй","" ],
	[ "geizig","жадный\nскупой","" ],
	[ "Gelehrter","учёный","" ],
	[ "Gelenk (Anat.)","сустав","" ],
	[ "gemein, schädlich\ngemein, niederträchtig","вредный\nподлый","" ],
	[ "Gemüsegarten","огород","" ],
	[ "Genuss","наслаждение","" ],
	[ "gepflegt, ordentlich, sauber, adrett","опрятный","" ],
	[ "gepunktet, getupft","в горошек","" ],
	[ "gerade Zahl / gerades Jahr\nungerade Zahl / ungerades Jahr","чётное число / чётный год\nнечётное число / нечётный год\n","" ],
	[ "Geräusch, Geraschel","шорох","" ],
	[ "Gericht, Speise, Essen, Mahlzeit","кушанье, -нья","" ],
	[ "geriebene Muskatnuss","натёртый мускатный орех","" ],
	[ "Gerste","ячмень м. (-ня)\nячменный","" ],
	[ "Geruchssinn","обоняние","" ],
	[ "geschäftig","деловитый","" ],
	[ "geschäftlich, dienstlich","по делам","" ],
	[ "Geschirrspülmaschine","посудомойка","" ],
	[ "geschmeichelt","польщённый","" ],
	[ "geschmolzen","растопленный","" ],
	[ "gesetzlicher Feiertag","нерабочый день","" ],
	[ "Gespenst","привидение","" ],
	[ "gesund; gesundheitsfördernd","целебный","" ],
	[ "Gesundheitsministerium","министерство здравоохранения","" ],
	[ "gewinnen","выигрывать - выиграть","" ],
	[ "Gewitter","гроза","" ],
	[ "Gewürz","специя\nпряность ж.\nприправа","" ],
	[ "Gießerei","литейный завод","" ],
	[ "Giftstoff","токсин","" ],
	[ "gipsen","штукатурить","" ],
	[ "Glacis nt. [gla‘]si\n(zum Feind hin flache, ins Vorfeld verlaufende Erdaufschüttung vor einem Festungsgraben, die keinen toten Winkel entstehen lässt)","гласис\nпологая земляная насыпь перед наружным рвом крепости (укрепления), возводимая с целью улучшения условий обстрела впереди лежащей местности, маскировки и защиты крепости (укрепления).","" ],
	[ "Glanz, Schein, Leuchten","сияние","" ],
	[ "Glashalter (mit Henkel)","подстаканик","" ],
	[ "glatt, rutschig","скользкий","" ],
	[ "Glatteis","гололёд\nгололедица","" ],
	[ "gleichartig, homogen; geschmeidig (Teig)","однородный","" ],
	[ "gleichberechtigt","равноправый","" ],
	[ "gleichfalls, ebenso, beiderseits","взаимно","" ],
	[ "Gleichgültigkeit","равнодушие\nбезразличие к кому-чему","" ],
	[ "gleichmäßig","равномерный","" ],
	[ "gleichnamige Erzählung","одноимённая сказка","" ],
	[ "glockenhell","звонкий как колокольчик","" ],
	[ "Glück","удача","" ],
	[ "Glücksspiele\n(leidenschaftlich)","азартные игры\n(азартный)","" ],
	[ "Glückwunschkarte","поздравительная открытка","" ],
	[ "gnädiges Fräulein","барышня","" ],
	[ "Göttin","богиня","" ],
	[ "Graben","ров, рва","" ],
	[ "Grenzbeamter","пограничник","" ],
	[ "grenzen an","граничить с кем-чем","" ],
	[ "groß\n\n\n(bedeutend)\n\n(von großem Umfang)","большой\nкрупный\nогромный\nвеликий\nзначимый\nздание масштабного объёма","" ],
	[ "großartig","здорово\nшикарный\nВыглядит всё шикарно","" ],
	[ "große Tasse","кружка","" ],
	[ "großes Aufsehen erregen","произвести настоящий фурор","" ],
	[ "Großfürstin","княгиня","" ],
	[ "großzügig, freigebig","щедрый","" ],
	[ "Grund-, Kardinalzahl","количественное числительное","" ],
	[ "Grundlagenforschung","фундаментальные исследования\nфундаментальная наука","" ],
	[ "gründlich","основательный","" ],
	[ "Gründonnerstag","Чистый четверг","" ],
	[ "grunzen (Schwein)","хрюкать","" ],
	[ "Gurgeln","полоскание горла","" ],
	[ "GUS – Gemeinschaft Unabhängiger Staaten","СНГ – содружество независимых государств","" ],
	[ "Gutes, Nützliches","добро","" ],
	[ "hacken (Holz)","накалывать - наколоть","" ],
	[ "hacken (Holz)\nhacken (Essen)","накалывать – наколоть\nнашинковать","" ],
	[ "Hafer\nHaferflocken","овёс (овса)\nовсяные хлопья","" ],
	[ "Hagel","град, града","" ],
	[ "Halbmond","полумесяц","" ],
	[ "Hallo, Hallöchen","привет, приветик","" ],
	[ "Halloween","Хеллоуин","" ],
	[ "Haltung / Einstellung gegenüber, Beziehung zu","отношение к кому-чему","" ],
	[ "Hamster","хомяк","" ],
	[ "handgeschriebene Variante","рукописный вариант","" ],
	[ "Handvoll","горсть ж. –ти","" ],
	[ "Handwerk","промысел, -сла","" ],
	[ "Handy","мобильник","" ],
	[ "Hängebrücke","подвесной мост\nвисячий мост","" ],
	[ "Hanswurst","шут гороховый","" ],
	[ "harntreibend","мочегонный","" ],
	[ "hartgekochtes Ei","яйцо вкрутую","" ],
	[ "hast du bereits kennengelernt","тебе уже встречались","" ],
	[ "hastig, hektisch","суетливый","" ],
	[ "häufig, oft","часто - чаще","" ],
	[ "Hauptsitz","штаб-квартира","" ],
	[ "Hauseingang, Auffahrt","подъезд","" ],
	[ "Haustier, Zögling","питомец","" ],
	[ "Haut, Schale, Fell, Leder","кожа\nшкура, шкурка","" ],
	[ "Hecht","щука","" ],
	[ "Heidelbeere, Schwarzbeere","черника","" ],
	[ "heilen","исцелять – исцелить\nлечить несов.","" ],
	[ "heilend","целебный","" ],
	[ "Heiligabend, der Heilige Abend","Рождественный сочельник","" ],
	[ "Heilkräutertee","целебный чай","" ],
	[ "heiß","горячий – горячее\nжаркий – жарче\nзнойный","" ],
	[ "Hektik, Betrieb","суета","" ],
	[ "Hektik, Eile, Hast","суета","" ],
	[ "hellblau","голубой","" ],
	[ "Hemd, Oberhemd\nHemd\nNachthemd","рубашка\nсорочка\nночная сорочка","" ],
	[ "herb","терпкий","" ],
	[ "hereinschneien (fig.)","свалиться как снег на голову","" ],
	[ "Herkunft\njd mit anderer Herkunft\nSie stammen aus Russlands berühmtester Aristokratendynastie","происхождение\nвыходец\nВы являетесь выходцем самой известной аристократической династии России","" ],
	[ "herunterladen (Datei)","скачивать – скачать (файл)","" ],
	[ "hervorragend, ausgezeichnet","превосходный","" ],
	[ "Herz-Kreislauf-System","сердечно-сосудистая система","" ],
	[ "heulen (Wolf)","выть несов.\nвою, воешь","" ],
	[ "Heulsuse","плакса","" ],
	[ "heute ist der zehnte Mai","сегодня десятое мая","" ],
	[ "heutzutage","в наши дни","" ],
	[ "Himbeere","малина","" ],
	[ "Himmelsrichtungen","стороны света","" ],
	[ "hin und her rollen, wälzen, wenden\n(eintauchen)","обваливать – обвалить\n\nобмакивать - обмакнуть","" ],
	[ "hindeuten auf, ankündigen","предвещать что? (несов.)","" ],
	[ "hinsichtlich, bezüglich","относительно (чего ?)","" ],
	[ "hitzköpfig","горячий,\nвспыльчивый,\nзапальчивый","" ],
	[ "HIV","вирус иммунодефицита человека","" ],
	[ "hoch","высоко - выше","" ],
	[ "hochladen (Datei)","загружать – загрузить (файл)","" ],
	[ "Hochland","плоскогорье","" ],
	[ "höflich, zuvorkommend","вежливый","" ],
	[ "Höhepunkt","кульминация","" ],
	[ "homogen\nhomogener Teig","однородный\nоднородное тесто","" ],
	[ "Homograph, -graf\nWort, das sich in der Aussprache von einem anderen gleich geschriebenen unterscheidet:\nTenor – Tenor\n\nHomonym („Teekesselchen“)\nWort, das mit einem anderen gleich lautet, den gleichen Wortkörper hat, aber in Bedeutung und Herkunft verschieden ist:\nBall; брак (Ehe; Mangel)","омограф\n(жаркое - Braten\nжаркое - heißes Wetter\nтрусы – Slip, Unterhose\nтрусы - Angsthasen\nдухи – Geister\nдухи - Parfüm\nзамок – Schloss, Burg\nзамок - Türschloss\nорган – Organ\nорган - Orgel\nхлопок – Baumwolle\nхлопок – Plopp, Klaps\nатлас – Atlas (Stoff)\nатлас – Atlas (Karte)\nобеспечение - Sicherheit\nобеспечение - Versorgung","" ],
	[ "Honigmelone","дынья","" ],
	[ "Hopfen","хмель м. (хмеля)","" ],
	[ "hören","слушать - послушать","" ],
	[ "Hörtraining","тренировка на слух","" ],
	[ "Hose","брюки\nштаны","" ],
	[ "Hubschrauber","вертолёт","" ],
	[ "Hülsenfrüchte","бобовые","" ],
	[ "hüpfen, springen","прыгать - прыгнуть","" ],
	[ "Husten","кашель, -ля м.","" ],
	[ "Hüter/in, Kurator/in, Vormund","опекун, опекунша","" ],
	[ "Hütte","избушка","" ],
	[ "ich habe uns je zwei Karten für … besorgt / reserviert / gebucht","я нам забронировал по два билета на","" ],
	[ "im Jugendslang","на молодёжном сленге","" ],
	[ "im Kaukasus","на Кавказе","" ],
	[ "im Laufe von anderthalb Jahren","в течение полутора лет","" ],
	[ "im späten 19. bis frühen 20. Jh","в конце XIX – начале XX века","" ],
	[ "im vorgeheizten Backofen","в предварительно разогретой духовке","" ],
	[ "imitieren","подражать","" ],
	[ "Imperativ","повелительное наклонение","" ],
	[ "in Bezug auf","насчёт\nЧто ты скажешь насчёт погоды?","" ],
	[ "in den mehr als 25 Jahren","более чем за 25 лет","" ],
	[ "in der betonten Silbe\nin der unbetonten Silbe\nin unbetonter Position","под ударением\nбез ударения\nв безударной позиции","" ],
	[ "in der ganzen Stadt","во всём городе","" ],
	[ "in der Nacht vom","в ночь с","" ],
	[ "in der Pause (Theater)","в антракте","" ],
	[ "in die Hocke gehen\nsich ducken, sich kleinmachen","присесть на корточки\nсидеть на корточках","" ],
	[ "in eine Liste eintragen\nin die Rote Liste eintragen / aufnehmen","заносить в список\nзаносить – занести в Красную книгу","" ],
	[ "in einem Wörterbuch","проверяй слова по словарю","" ],
	[ "in einer trockenen Pfanne","на сухой сковороде","" ],
	[ "in heidnischen Zeiten","в языческие времена","" ],
	[ "in Ordnung bringen","приводить – привести в порядок","" ],
	[ "in Vergessenheit geraten, vergessen\netwas vergessen","подзабывать – подзабыть\n\nзабыть про что / кого\nя забыла про лимон","" ],
	[ "in Worten schreiben, ausschreiben","написать прописью","" ],
	[ "in(nnerhalb von) sechs Tagen","Бог создал Землю за шесть дней","" ],
	[ "Indefinitpronomen","неопределённое местоимение\n(где-нибудь, где-то, чём-то, куда-то, как-нибудь, куда-нибудь и т. д.)","" ],
	[ "Ingwer","имбирь м.","" ],
	[ "Inspiration","вдохновение","" ],
	[ "Intelligente Sprachlernsysteme, die heute existieren, haben ein  ziemlich breites Anwendungsspektrum","Существующие на сегодня ителлектуальные системы изучения иностранных языков имеют достаточно широкие области применения","" ],
	[ "international anerkannt","с мировым имением","" ],
	[ "Internationales Olympisches Komitee (IOC)","МОК – Международный Олимпийский Комитет","" ],
	[ "Internetseite, Webseite, Site","страничка","" ],
	[ "Internetshop","интернет-магазин","" ],
	[ "ist das etwa …","неужели это ...","" ],
	[ "Jahresbeitrag","годовой взнос","" ],
	[ "Jahrestag","годовщина\nСегодня исполняется 225 лет со дня рождения А. С. Пушкина (6 июлья 2024)","" ],
	[ "jdm / einer Sache nachstehen\nDie Greifenbrücke steht den Zugbrücken in ihrer Schönheit in nichts nach / ist ebenso schön wie","уступать кому-чему\nБанковский мост своей красотой она совсем не уступает разводным мостам.","" ],
	[ "jdm die Sprache verschlagen","лишить кого-л. дара речи","" ],
	[ "jdm etwas beibringen, jdn etwas lehren","учить кого-л. что-л.\nОн учит Антона","" ],
	[ "jdm etwas widmen","посвящать – посвятить кому-л. что-л.","" ],
	[ "jdm etwas wünschen","желать кому чего","" ],
	[ "jdm gratulieren zu","поздравлять – поздравить кого с чем","" ],
	[ "jdn beauftragen, etwas zu tun","поручить кому-л. делать что-л.","" ],
	[ "jdn grüßen\nsich grüßen","здороваться с к кем\nздороваться","" ],
	[ "jdn grüßen, jdm Grüße übermitteln","передать кому-либо привет","" ],
	[ "jdn grüßen, jdm Grüße übermitteln","передать кому-либо привет","" ],
	[ "jdn hat Glück","кому везёт","" ],
	[ "jdn heiraten (eine Frau)\njdn heiraten (einen Mann)","жениться на ком\nвыйти замуж на ком","" ],
	[ "jdn interviewen","брать - взять у кого интервью","" ],
	[ "jdn keines Blickes würdigen","не удостаивать кого взглядом","" ],
	[ "jdn krankschreiben, jdm eine AU / Arbeitsunfähigkeitsbescheinigung geben","выдавать – выдать кому-либо больничный лист","" ],
	[ "Jerusalem","Иерусалим","" ],
	[ "Jesus Christus","Иисус Христос","" ],
	[ "Jod","йод","" ],
	[ "Joggen","пробежка","" ],
	[ "joggen (im Trab laufen)","бегать трусцой","" ],
	[ "Jogurt","йогурт","" ],
	[ "Johannes der Täufer\n(Vorbote, Vorläufer)","Иоанна Предтечи\nпредчета ","" ],
	[ "Jubiläum","годовщина","" ],
	[ "junge Frau","девушка","" ],
	[ "junger Mann","парень","" ],
	[ "Käfer","жук","" ],
	[ "Kaffeemaschine","кофеварка","" ],
	[ "Kaffeetasse","чашка","" ],
	[ "Kaisernatron","пищевая сода","" ],
	[ "Kaki","хурма","" ],
	[ "kalt","холодный - холоднее","" ],
	[ "kaltgepresst","сырого отжима","" ],
	[ "kameradschaftlich","дружеский","" ],
	[ "Kar-\nKarwoche\nKarfreitag","страстной\nстрастная неделя\nстрастная пятница","" ],
	[ "Karaffe","графин","" ],
	[ "Karfreitag","Страстная пятница","" ],
	[ "Kasus, Fall\nNominativ\nGenitiv\nDativ\nAkkusativ\nInstrumental\nPräpositiv","падеж, (-а)\nименительный п.\nродительный п.\nдательный п.\nвинительный п.\nтворительный п.\nпредложный п.","" ],
	[ "Kasus, Fall\nNominativ\nGenitiv\nDativ\nAkkusativ\nInstrumentalis\nPräpositiv","падеж\nименительный\nродительный\nдательный\nвинительный\nтворительнй\nпредложный","" ],
	[ "Kattun- , Kaliko- m. (feines dichtes Baumwollgewebe)","ситцевый","" ],
	[ "Kaufleute","купечество","" ],
	[ "keine Ursache","не за что","" ],
	[ "keinesfalls, auf keinen Fall","ни в коем случае\nникоим образом\nникак не ....","" ],
	[ "Keller","погреб, (-а)","" ],
	[ "Kellner","официант","" ],
	[ "Kenner, Experte","знаток, -а","" ],
	[ "Kerngehäuse\nKern, Kernstück (fig.)","сердцевина, семенные коробки","" ],
	[ "Kiefer (Baum)","сосна","" ],
	[ "Kies","галька","" ],
	[ "Kinderkrippe, Futterkrippe","ясли, яслей","" ],
	[ "Kinderreim","детская считалочка","" ],
	[ "Kirchenjahr","богослужебный год","" ],
	[ "Klappbett","раскладушка","" ],
	[ "Klassentreffen","день встречи выпускников","" ],
	[ "Klebeband","скотч","" ],
	[ "Kleiderbügel","вешалка","" ],
	[ "Kleiderschrank","платяной шкаф","" ],
	[ "klein","маленький, меньше\nнебольшой","" ],
	[ "klein schneiden (Zwiebel)","нашинковывать - нашинковать (лук)","" ],
	[ "kleines Schnapsgläschen für 50 ml","стопка на 50 мл\nрюмка на 50 мл","" ],
	[ "klicken (Computer, Handy)","нажимать","" ],
	[ "Knoblauchpresse","чеснокодавилка","" ],
	[ "Knoblauchzehe","зубчик чеснока","" ],
	[ "Knollen, Klumpen","ком","" ],
	[ "Knollenzwiebel","репчатый лук","" ],
	[ "Knospe; Niere","почка","" ],
	[ "kochen","печь - испечь","" ],
	[ "kochendes Wasser","вар","" ],
	[ "Kochkunst","кулинария","" ],
	[ "kohlrabenschwarz","чёрный как ночь","" ],
	[ "kombinieren mit","совмещать - совместить с чем-либо","" ],
	[ "kommen zu\nWie kommst du zur Arbeit?","добираться – добраться\nКак ты добираешся на работу?","" ],
	[ "Kommunikationsmittel","средство общения","" ],
	[ "Komparativ","сравнительная степень\nузко – уже\nплохо – хуже\nтихо – тише\nчасто – чаще\nнизко – ниже\nвысоко – выше\nшироко – шире\nблизко – ближе\nрано – раньше\nхорошо – лучше\nмало - меньше","" ],
	[ "König\nKönigin","король\nкоролева","" ],
	[ "Konjugation\nkonjugieren","спряжение\nспрягать – проспрягать","" ],
	[ "konjugieren\nebenso werden konjugiert","спрягать – поспрягать\nтак же спрягаются","" ],
	[ "Konjunktiv","сослогательное наклонение","" ],
	[ "können\nhier kannst du die Route sehen","\nздесь можно тебе посмотреть маршрут","" ],
	[ "Konsonantenwechsel","чередование согласных","" ],
	[ "kontaktfreudig, gesellig, aufgeschlossen, kommunikativ","общительный","" ],
	[ "Koriander","кориандр\nкинза","" ],
	[ "Kornelkirsche","кизил","" ],
	[ "Kragen","воротник","" ],
	[ "krähen","кукарекать","" ],
	[ "Krämer","торгаш","" ],
	[ "Krankenpfleger","санитар","" ],
	[ "Krankenversicherung","медицинская страховка","" ],
	[ "kranksein; mitfiebern, Fan sein","я болею, ты болеешь, он болеет\nмы болеем, вы болеете, они болеют","" ],
	[ "Kranz","венок, венка","" ],
	[ "Kranz","венок, венка","" ],
	[ "Krapfen, Berliner","пончик","" ],
	[ "Kräuter, Grün(zeug)\nwürziges Kraut, Küchenkraut","зелень ж\nпряная трава","" ],
	[ "Kräuterlikör","бальзам","" ],
	[ "Kreativität, Schaffenskraft","творчество","" ],
	[ "krebsrot","красный как рак","" ],
	[ "Kreide","мел","" ],
	[ "kreuzigen","распинать - распять","" ],
	[ "Krimi","детектив","" ],
	[ "Kringel (Gebäck)","баранка","" ],
	[ "Krug\nkrugförmig","кувшин\nкувшинообразный","" ],
	[ "Kruste (Braten, Zitrusfrucht)","корочка","" ],
	[ "Kuchen \n\n(klein)","пирог\nкекс\nпирожное","" ],
	[ "Küken, Brathähnchen","цыплёнок","" ],
	[ "künstliche Intelligenz","искуственный ителлект","" ],
	[ "Kürbis","тыква","" ],
	[ "Kurier","курьер","" ],
	[ "Kurse besuchen","ходить на курсы","" ],
	[ "Kurse besuchen","ходить на курсы","" ],
	[ "kurz","коротко - короче","" ],
	[ "Kurzwaren","галантерея","" ],
	[ "Küste","побережье","" ],
	[ "lachen","смеяться - засмеяться","" ],
	[ "Lagerfeuer","костёр, костра","" ],
	[ "Landesgrenze","сухопутная граница","" ],
	[ "Landgut","усадьба","" ],
	[ "Landgut, Gut (außerhalb der Stadt)","(загородное) имение","" ],
	[ "Landstreitkräfte","сухопутный воиски","" ],
	[ "lang (örtlich)\nlang (zeitlich)","длинный - длиннее\nдолго - дольше","" ],
	[ "Laptop, Notebook","ноутбук","" ],
	[ "lassen","оставлять - оставить","" ],
	[ "laut","громко - громче","" ],
	[ "laut vorlesen","читать вслух","" ],
	[ "leben, wohnen","жить - прожить","" ],
	[ "Leber (Anat.)","печень, -ни ж.","" ],
	[ "lebhaft (Persönlichkeit)\nlehbhaft (Atmosphäre)","яркий (индивидуальность)\nсуета","" ],
	[ "Leckerei","лакомство","" ],
	[ "Leckerei","вкусняшка (разг.)","" ],
	[ "Leckermaul, Schleckermäulchen","сладкоежка","" ],
	[ "legen\nlegen, ausstellen (для обозрения);\nsagen, auspacken (высказывать) \nverlegen (отделывать) \naufbauen (соорудить)\nsich legen","класть – положить\nвыкладывать – выложить\n\n\n\n\nложиться - лечь","" ],
	[ "Leggin(g)s","лосины","" ],
	[ "Lehnwort","заимствованное слово","" ],
	[ "Lehrer\nHochschullehrer, Dozent, Lektor","учитель\nпреподаватель","" ],
	[ "lehrreich","поучительный","" ],
	[ "Leiche","труп","" ],
	[ "Leichtsinn","легкомыслие","" ],
	[ "leichtsinnig","легкомысленный","" ],
	[ "leidenschaftlich, feurig, begeistert","страстный","" ],
	[ "Leiter, Anführer, Spielleiter","ведущий","" ],
	[ "Lerche","жаворонок","" ],
	[ "lernen, erlernen, studieren (was?)","изучать – изучить\n","В институте я изучал(а) физику, химию, биологию, право и латинский.\nЯ изучаю информатику.\nЯ люблю изучать иностранные языки." ],
	[ "lernen, fertig lernen (was?)","учить – выучить","В одиннадцатом классе ребята учат/учили астрономию.\nТы ведь не учишь не для экзамена, а для жизни.\nРекотендую его (русский язык) учить всем.\nСегодня она хочет (вы)учить все новые слова.\nСлова можно выучить.\nТы выучил(а) много слов.\nЯ хочу выучить русский язык.\nТы уже выучил(а) много воспросительных слов\nПочему иностранцы учат русский язык?\nИногда их (новые слова) не получается хорошо выучить.\nУчи слова с ударением" ],
	[ "lernen, sich beschäftigen mit\nMit welchem Lehrbuch lernst du?","заниматься чем"," По какому учебнику ты занимаешься?" ],
	[ "lernen, studieren (wo?)","учиться – научиться чему","На медицинском университете студенты учатся шесть лет.\nОна учится на факультете информатики. \nОна учится в классе со спортивным уклоном.\nОна учится в гимназии. Там она учит математику.\nОн учится в техническом университете прикладных наук.\nЯ много научился.\nОн быстро научился играть в хоккей.\nЯ хочу научиться делать кисель из клюквы\nОна ужасно хочет научиться торговаться.\nЯ учу каждый день новые слова.\nА почему ты учишь русский язык?\nДелаем покупки и учимся новому." ],
	[ "lese- und schreibkundig","грамотный","" ],
	[ "lesen\nins Lesen vertieft sein","читать – прочитать\nзачитаться","" ],
	[ "Lettland\nLette, Lettin","Латвия\nлатыш, латышка","" ],
	[ "letzte Woche ","на прошлой неделе мы купили","" ],
	[ "Liebe auf den ersten Blick","любовь с первого взгляда","" ],
	[ "Likörglas","рюмка","" ],
	[ "Limonadenglas","стакан","" ],
	[ "Link","ссылка","" ],
	[ "Linkshänder","левша, -ши\nрод. мн. -шей","" ],
	[ "Linsen","чечевица","" ],
	[ "Litauen\nLitauer, Litauerin","Литва\nлитовец, литовка","" ],
	[ "live","в прямом эфире","" ],
	[ "Live-Sendung","прямой эфир","" ],
	[ "Locher","дырокол","" ],
	[ "Löschschaum","огнетушащая пена","" ],
	[ "Löwenzahn","одуванчик","" ],
	[ "Lücke","пропуск","" ],
	[ "lüften\nsich erfrischen","проветриваться - проветриться","" ],
	[ "Luke","люк","" ],
	[ "lustig","забавный","" ],
	[ "mach dir keine Sorgen","не переживай","" ],
	[ "Magengeschwür","язвенная болезнь","" ],
	[ "mager","постный","" ],
	[ "magisch","волшебный","" ],
	[ "Magisterstudium","магистратура","" ],
	[ "Mahl (an einer Tafel)","трапеза","" ],
	[ "Maiglöckchen","ландыш","" ],
	[ "Make-up, Schminke","макияж","" ],
	[ "malen, zeichnen","рисовать - нарисовать","" ],
	[ "Malerei, Bemalung; Unterschrift","роспись\nживопись","" ],
	[ "malerisch","живописный","" ],
	[ "Malz","солод","" ],
	[ "Mandelmilch","миндальное молоко","" ],
	[ "Mangel","брак","" ],
	[ "Männchen","самец","" ],
	[ "Märchenfilm","фильм-сказка","" ],
	[ "markiert, hervorgehoben","выделенный","" ],
	[ "Maskenbildner","гримёр","" ],
	[ "Massenmedien","СМИ - средства массовой информации","" ],
	[ "Material zu Grammatik","материал по грамматике","" ],
	[ "Meinungsfreiheit","свобода слова","" ],
	[ "Meinungsverschiedenheit, Widerspruch, Diskrepanz, Differenz, Dissens, Streitgegenstand","разногласие","" ],
	[ "Messe (Wirtsch.)","ярмарка; выставка","" ],
	[ "Messerspitze","на кончике ножа","" ],
	[ "Metapher","метафора","" ],
	[ "Meteorologe","синоптик","" ],
	[ "mieten","арендовать\nснимать – снять (квартиру)","" ],
	[ "Milchsäuregärung","молочнокислое брожение","" ],
	[ "Millionenstadt\n(Pl)","город-миллионник\nгорода-миллионники","" ],
	[ "Mineralstoff","минеральное вещество","" ],
	[ "Minze\nPfefferminze\nMinzeis","мята\nперечная мята\nмятное мороженое","" ],
	[ "mir fällt es leicht","мне даётся легко","" ],
	[ "mir ist übel","меня тошнит","" ],
	[ "Missverständnis, Versehen","недоразумение","" ],
	[ "Mist! Verdammt!","Блин!","" ],
	[ "mit 30 Jahren (als er 30 war)\n\nmit 6 (Jahren)\nmit 9","к тридцати годам\nкогда ему было 30\nв шесть лет\nв 9","" ],
	[ "mit 30 Jahren (als er 30 war)\n\nmit 6 (Jahren)\nmit 9","к тридцати годам\nкогда ему было 30\nв шесть лет\nв 9","" ],
	[ "mit sich führen","везти – повезти с собой","" ],
	[ "Mitbewohner","товарищ по общежитию","" ],
	[ "miteinander kommunizieren\nkommunizieren / chatten im Forum, auf WhatsApp, Telegram, Facebook","пообщаться друг с другом\nобщаться в форуме, Ватсапе, Телеграме, Фейсбуке","" ],
	[ "Mitreisender","попутчик","" ],
	[ "Mittelmeer","Средиземное море","" ],
	[ "mittlerweile","к настоящему времени","" ],
	[ "Moltebeere","морошка","" ],
	[ "mondän","богема","" ],
	[ "Montenegro","Черногория","" ],
	[ "Moosbeere","клюква","" ],
	[ "morgens","по утрам","" ],
	[ "Motorboot","катер","" ],
	[ "Möwe","чайка","" ],
	[ "MP3-Player","MP3-плеер","" ],
	[ "muhen","мычать","" ],
	[ "Musikwissenschaftler","музыковед","" ],
	[ "mutig","храбрый","" ],
	[ "Mutter","мать - матери","" ],
	[ "nach Geschmack / Belieben","по вкусу","" ],
	[ "nach Jahreszeiten","рассортируй по временам года","" ],
	[ "Nach russischer Tradition wird eine gerade Anzahl an Blumen nur zu Beerdigungen und Gräbern gebracht","По русской традиции чётное количество цветов приносят только на похороны и могилы.","" ],
	[ "Nachahmung\nVorbild","подражание\nобразец для подражания","" ],
	[ "Nachsicht","снисхождение","" ],
	[ "Nachtigall","соловей","" ],
	[ "nachts","ночью\nв ночные часы","" ],
	[ "Nachttisch","тумбочка","" ],
	[ "Nagel (Metallstift)\nNagel (Anat.)\nden Nagel auf den Kopf treffen","гвоздь м.\nноготь м.\nпопасть в точку","" ],
	[ "nah","близко - ближе","" ],
	[ "nahöstlich","ближневосточный","" ],
	[ "Nährstoff","питательное вещество","" ],
	[ "nährstoffreiche Nahrung","богатая питательными веществами пища","" ],
	[ "Namenstag\nalles Gute zum Namenstag","именины\nс днём именин","" ],
	[ "Narr","шут","" ],
	[ "Naschkatze","сладкоежка","" ],
	[ "Naseweis","выскочка","" ],
	[ "Nebenbetonung","побочное ударение","" ],
	[ "Neffe\nNichte","племянник\nплемянница","" ],
	[ "nehmen\nwoher soll ich sie für dich nehmen?","брать – взять\nгде я тебе её возьму?","" ],
	[ "Nehrung","стрелка","" ],
	[ "Nennwert, Stückelung","номинал\nсерия банкнот включает в себя номиналы 10, 50, 100 ... рублей","" ],
	[ "Nervensäge","почемучка","" ],
	[ "neugierig","любопытный","" ],
	[ "nicht ausgesprochener (stummer) Konsonant","непроизносимый согласный (звук)","" ],
	[ "nicht zu groß","некрупный","" ],
	[ "niedrig","низко - ниже","" ],
	[ "Niere","почка","" ],
	[ "Nordic Walking","северная ходьба","" ],
	[ "Nordsee","Северное море","" ],
	[ "Notfallnummer","номер экстренных служб","" ],
	[ "nützlich - nützlicher","полезный - полезнее","" ],
	[ "oben rechts","наверху справа","" ],
	[ "objektiv","объективный","" ],
	[ "obligatorisch","обязательный","" ],
	[ "Ofenasche","печная зола","" ],
	[ "Ohr, Ohren","ухо, уши","" ],
	[ "okay","окей","" ],
	[ "Olive","маслина","" ],
	[ "Olympisches Komitee Russlands","ОКР – олимпийский комитет России","" ],
	[ "Opernstar","оперная звезда","" ],
	[ "Ordnungszahl","порядковое числительное","" ],
	[ "Osterbrot, -kuchen","кулич","" ],
	[ "Osterfest","праздник Пасхи","" ],
	[ "OTH","Восточно-Баварский технический университет прикладных наук","" ],
	[ "Palindrom (Wort das vorwärts und rückwärts gelesen gleich ist)\nda/hier, jener/derjenige, alter Mann/Großvater, Bestellung, Kosak, Getrampel, Klumpen/Knäuel, (Laub)Hütte","палиндром\n\nтут, тот, дед, заказ, казак, топот, комок, шалаш","" ],
	[ "Palmsonntag","вербное воскресенье","" ],
	[ "Paniermehl","панировочные сухари","" ],
	[ "Paprika(schote)","болгарский перец","" ],
	[ "Party\nGeschäftsparty","вечеринка\nкопоративная вечеринка","" ],
	[ "Pause","антракт","" ],
	[ "Pechvogel","неудачник","" ],
	[ "Pelz-","меховой","" ],
	[ "Personalpronomen","личное местоимение","" ],
	[ "Pfanne","сковородка\nсковорода","" ],
	[ "Pfannkuchen, Plinse","блин, -на","" ],
	[ "pfeffern","перчить - поперчить","" ],
	[ "Pferdefleisch","конина","" ],
	[ "Pflanzenöl","растительное масло","" ],
	[ "pflegen","ухаживать несов. в.","" ],
	[ "Pforte, Zauntor","калитка","" ],
	[ "piepsen (Maus)","пищать","" ],
	[ "planmäßig ankommen","прийти по расписанию","" ],
	[ "planmäßig ankommen","прийти по расписанию","" ],
	[ "plaudern","сплетничать - посплетничать","" ],
	[ "Polarlicht, Nordlicht","полярное сияние","" ],
	[ "Pommes frites","картошка фри","" ],
	[ "Possessivpronomen","притяжательное местоимение","" ],
	[ "Postbote","почтальон","" ],
	[ "Preis (Auszeichnung)","премия","" ],
	[ "Preiselbeere","брусника","" ],
	[ "Prise","щепотка (чего)","" ],
	[ "Probe (Theater u. dgl.)","репетиция","" ],
	[ "probieren, ausprobieren","пробовать - попробовать","" ],
	[ "Produktionshalle","цех","" ],
	[ "Qual","мука","" ],
	[ "Quarkpuffer","сырники","" ],
	[ "Quitte","айва","" ],
	[ "Rabatt\nHerbstrabatt","скидка\nскидка по осенней акции","" ],
	[ "Radiergummi","ластик","" ],
	[ "Rätsel, Quiz","викторина","" ],
	[ "rau (Klima)","суровый","" ],
	[ "Raucher","курильщик","" ],
	[ "Raum, Räumlichkeit","помещение","" ],
	[ "Raumschiff","космический корабль","" ],
	[ "Rechtschreibung","правописание","" ],
	[ "rechtzeitig, im Voraus","заблаговременно","" ],
	[ "Reflexivverb","возвратный глагол","" ],
	[ "Reibe, Reibeisen","тёрка","" ],
	[ "reichen, servieren","подавать несов. в.","" ],
	[ "reif","спелый","" ],
	[ "Reim","рифма","" ],
	[ "reimen\nsich reimen auf / mit","рифмовать c\nрифмоваться с","" ],
	[ "reisen, fliegen nach","прилетать в (куда)","" ],
	[ "Reisender","путешественник","" ],
	[ "Rendez-vous","рандеву","" ],
	[ "Reservierung (eines Tisches)","бронирование стола","" ],
	[ "Ritter","рыцарь","" ],
	[ "Roaming","роуминг","" ],
	[ "Roggen","рожь ж., ржи","" ],
	[ "Roller, Skooter","самоскат","" ],
	[ "rote / schwarze Johannisbeere","красная / чёрная смородина","" ],
	[ "Ruhm","слава","" ],
	[ "russisch","русский или российский\nрусский – мой родной язык\nрусский язык\nроссийский\nроссийские артисты\nроссийский дом \nроссийские исследователи\nроссийская культура\nроссийская поп-звезда\nроссийские учителя","" ],
	[ "russischsprachig","русскоязычный","" ],
	[ "säen","сеять - посеять","" ],
	[ "sagen, sprechen","говорить - сказать","" ],
	[ "Sahneeiscreme am Stiel mit Schokoladenglasur","эскимо","" ],
	[ "Saite","струна","" ],
	[ "Sakrament","таинство","" ],
	[ "Salatschüssel","салатница","" ],
	[ "Salbei","шалфей м.","" ],
	[ "salzen","солить – засолить / посолить","" ],
	[ "samten, Samt-","бархатный","" ],
	[ "Sandale","сандалия","" ],
	[ "Sandaletten","босоножки","" ],
	[ "sanft, mild","кроткий","" ],
	[ "Sanftmut","кротость ж.","" ],
	[ "Satzung, Charta, Statut, Regel","устав","" ],
	[ "Sauerampfer","щавель","" ],
	[ "Sauerkirsche","вишня","" ],
	[ "Sauerkraut","квашеная капуста","" ],
	[ "Sauerstoff","кислород","" ],
	[ "Säugetier","мелкопитающий","" ],
	[ "Schaffner","проводник","" ],
	[ "Schale (Frucht, Gemüse)\nSchale (Ei, Nuss)\nSchale, Pelle, Hülse","кожура, мундир\nскорлупа\nшелуха","" ],
	[ "schälen, entfernen","очищать – очистить от ","" ],
	[ "scharfsinnig","проницательный","" ],
	[ "scharlachrot","алый","" ],
	[ "Schatten-, schattig","теневой","" ],
	[ "Schattierung","оттенок","" ],
	[ "Schatz","сокровище","" ],
	[ "Schatzkammer","сокровищница","" ],
	[ "schaukeln","качаться на качелях","" ],
	[ "Schaum","пена","" ],
	[ "schaumig, fluffig","пенистый","" ],
	[ "Schauspieler\nSchauspielerin","актёр\nактриса","" ],
	[ "scheußlich","мерзкий","" ],
	[ "schick","шикарный","" ],
	[ "schief, schräg","пологий","" ],
	[ "Schimpfwort","ругательство","" ],
	[ "Schirmherr, Schutzherr, Patron","покровитель, покровительница","" ],
	[ "Schlaflosigkeit","бессонница","" ],
	[ "Schlauheit","хитрость\nухватка","" ],
	[ "Schleife","бант","" ],
	[ "Schloss-Museum","музей-усадьба","" ],
	[ "Schmarotzer","бездельник","" ],
	[ "Schmaus","объедение","" ],
	[ "Schmeichelei, Schöntuerei","лесть ж.","" ],
	[ "Schmierheft, -papier","черновик","" ],
	[ "Schneefall\nleichter Schnee, Schneeball","снегопад\nснегжок","" ],
	[ "Schneeflocke","снежинка","" ],
	[ "Schneegestöber","метель ж., -ли","" ],
	[ "Schneeglöckchen","подснежник","" ],
	[ "Schneemann","снеговик","" ],
	[ "Schneeschmelze","оттепель ж. -ли","" ],
	[ "Schneesturm","пурга","" ],
	[ "Schneewittchen","Белоснежка","" ],
	[ "Schneider\nSchneiderin","портной\nпортниГ","" ],
	[ "Schnupfen","насморк","" ],
	[ "Schnurrbart","ус","" ],
	[ "Schnurren","мурлыкание","" ],
	[ "schnurren (Katze)","мурлыкать","" ],
	[ "schön","красивый - красивее","" ],
	[ "Schraube","шуруп","" ],
	[ "Schreibheft, -trainer","тетрадь для прописи","" ],
	[ "Schreibschrift\nschreibe in Schreibschrift","пропись ж\nнапиши прописью","" ],
	[ "Schreibwaren","канцелярские товары\nканцтовары","" ],
	[ "Schrift\nslawische Schrift","письменность ж.\nславянская письменность","" ],
	[ "Schriftsteller","писатель","" ],
	[ "schüchtern","робкий","" ],
	[ "Schüchternheit","скромность ж","" ],
	[ "schütten, aus, verschütten, ausstreuen\nschütte, schüttet (Imp.)","высыпать – высыпать\n\nвысыпь, -те","" ],
	[ "schweigend, schweigsam","безмолвный","" ],
	[ "Schwester","сестра - сёстры","" ],
	[ "Schwiegermutter","тёща (мать жены)\nсвекровь (мать мужа)","" ],
	[ "Schwiegervater","тесть (отец жены)\nсвёкор (отец мужа)","" ],
	[ "Schwimmbrille","плавательные очки","" ],
	[ "Science-Fiction","фантастика","" ],
	[ "scrollen","листать\nпрокручивать - прокрутить","" ],
	[ "See","oзеро, озёра мн.","" ],
	[ "Seefahrer","мореплаватель","" ],
	[ "Seehund, Robbe","тюлень ж., -ни","" ],
	[ "Seele\nsich in fremde Angelegenheiten einmischen\nvon ganzem Herzen lachen\nein Herz und eine Seele sein\nein mulmiges Gefühl haben","душа\nЛезть в душу\n\nСмеяться от души\nЖить душа в душу\nКошки скребут на душе","" ],
	[ "sehen\nlange nicht gesehen","видеть – увидеть\nсколько лет, сколько зим","" ],
	[ "sei nicht traurig\nin Verwirrung geraten; \nnicht zustande kommen;\nverstimmt sein, \nzerrüttet werden","не расстраивайся\nрасстраиваться - расстроиться","" ],
	[ "seine Gefühle ausdrücken","передать свои чувства","" ],
	[ "Seit den Tagen der Kiewer Rus","Ещё со времён Киевской Руси","" ],
	[ "Sektglas","бокал","" ],
	[ "Selbstfindung","самопознание","" ],
	[ "selbstgemacht","самодельный","" ],
	[ "selbstsicher","уверенный в себе","" ],
	[ "selten","редко - реже","" ],
	[ "Semmelbrösel","тёртый хлеб","" ],
	[ "Sesamöl ","кунжутное масло","" ],
	[ "Sibirier","сибиряк, сибиряки","" ],
	[ "sich amüsieren","забавляться","" ],
	[ "sich aufregen","расстраиваться - расстроиться","" ],
	[ "sich ausloggen","выходить","" ],
	[ "sich befinden, liegen","распологаться - расположиться","" ],
	[ "sich behaupten","закрепиться","" ],
	[ "sich einloggen","входить","" ],
	[ "sich einprägen / merken; \nsich erinnern\nmerke es dir! (schreibe dir das hinter die Ohren)","запоминать – запомнить\n\nмотай себе на ус!","" ],
	[ "sich entspannen","расслабляться - расслабиться","" ],
	[ "sich ergötzen, sich erfreuen an","любоваться чем","" ],
	[ "sich freuen über","радоваться чему","" ],
	[ "sich gegenseitig auf den Arm nehmen (spaßen)","разыгрывать друг друга","" ],
	[ "sich grämen, trauern um / über","горевать - погоревать","" ],
	[ "sich großer Beliebtheit erfreuen\n","пользоваться большой популярностью","" ],
	[ "sich in jdn verlieben","втюриваться – втюриться в кого","" ],
	[ "sich kindisch / wie ein Kind benehmen","ребячиться","" ],
	[ "sich kreuzen, sich überschneiden","пересекаться - пересечься","" ],
	[ "sich merken","запоминать - запомнить","" ],
	[ "sich per Skype unterhalten","общаться по скайпу","" ],
	[ "sich tarnen","маскироваться","" ],
	[ "sich verachtfachen","увеличить в 8 раз","" ],
	[ "sich verknallen","по уши влюбиться в кого (сов. в.)","" ],
	[ "sich verletzen","пораниться","" ],
	[ "sich wenden an\n\nDu musst sofort die Polizei unter der 102 anrufen","обращаться - обратиться к кому-либо\nТебе нужно срочно обратиться в полицию по номеру 102","" ],
	[ "sich zum Narren machen, Witze reißen","дурачиться","" ],
	[ "Siedlung","посёлок","" ],
	[ "Silbe","слог","" ],
	[ "Silvester / Neujahr","Новый Год","" ],
	[ "singen","петь - спеть","" ],
	[ "sinken, heruntergehen","опускаться – опуститься\nмороз опускается до – 50°C","" ],
	[ "Sinn, Wesen, Kern, Hauptsache","суть ж. (сути)","" ],
	[ "Skisport","лыжный спорт","" ],
	[ "skizzieren, entwerfen, zeichnen","чертить - начертить","" ],
	[ "Skript","конспект","" ],
	[ "Small Talk","светский разговор","" ],
	[ "so lala (Befinden)","не очень","" ],
	[ "so lange, bis","до тех пор, пока","" ],
	[ "so was!","вот это да!","" ],
	[ "Sodbrennen","изжога","" ],
	[ "Sohn","сын - сыновья","" ],
	[ "Sommersonnenwende","солнцестояние","" ],
	[ "Sonnenblume","подсолнух","" ],
	[ "Sonnenblumenkerne","семечко подсолнуха","" ],
	[ "Sonnenbrille","солнцезащитные очки","" ],
	[ "Sonnencreme","крем для загара","" ],
	[ "Sorglosigkeit, Unbekümmertheit","беззаботность","" ],
	[ "Soße aus Meerrettich, Tomaten…","соус на основе хрена, томатов...","" ],
	[ "Soße, Sauce, Saft","подливка","" ],
	[ "spachteln","шпаклевать","" ],
	[ "Spaß, Vergnügen, Zerstreuung","развлечение","" ],
	[ "spät","поздно - позже","" ],
	[ "Speck","сало","" ],
	[ "Spickzettel","шпаргалка","" ],
	[ "Spiegelei","яичница [-шн-]-глазунья\n","" ],
	[ "spielen (Sportart)\n(Musikinstrument)","играть в + вин. пад.\nиграть на + предл. пад.","" ],
	[ "Spieler","игрок, -ка","" ],
	[ "Spielfilm","художественный фильм","" ],
	[ "Sport treiben","заниматься спортом","" ],
	[ "Sport-, Turn-, Laufschuhe","кроссовки","" ],
	[ "Sportereignis","спортивное мероприятие","" ],
	[ "Sportschiedsgericht\nCAS (Court of Arbitration for Sport)","Спортивный арбитражный суд","" ],
	[ "Sprachlernsystem","система изучения иностранных языков","" ],
	[ "Sprechstunden","приёмные часы\nчасы приёма","" ],
	[ "Sprichwort","поговорка\nпословица","" ],
	[ "Staatsbürger / Einwohner Russlands","россиянин","" ],
	[ "Stachelbeere","крыжовник","" ],
	[ "Stadtviertel, Bezirk, Region, Gegend","район","" ],
	[ "Stadtwerke","жилищно-коммунальное хозяйство","" ],
	[ "Stamm (ling.)","основа","" ],
	[ "stammverwandt\nstammverwandte Wörter","однокоренной\nоднокоренные слова","" ],
	[ "stammverwandte Wörter","однокоренные слова","" ],
	[ "Standesamt","ЗАГС\nзапись актов гражданского состояния","" ],
	[ "Standesbeamter","сотрудник ЗАГСа","" ],
	[ "stattfinden","проходить","" ],
	[ "Staub saugen","пылесосить - пропылесосить","" ],
	[ "Staub wischen","стирать пыль ж.","" ],
	[ "Staub wischen","стирать пыль ж.","" ],
	[ "stechend (Schmerz)","острый","" ],
	[ "Stehlampe, -leuchte","торшер","" ],
	[ "Sternbild","созвездие","" ],
	[ "Sternzeichen\nSteinbock\nWassermann\nFische\nWidder\nStier\nZwilling\nKrebs\nLöwe\nJungfrau\nWaage\nSkorpion\nSchütze","знак зодиака\nКозерог\nВодолей\nРыбы\nОвен\nТелец\nБлизнецы\nРак\nЛев\nДева\nВесы\nСкорпион\nСтрелец","" ],
	[ "still, ruhig","тихо - тише","" ],
	[ "stimmhafter Konsonant\nstimmloser Konsonant","звонкий согласный\nглухой согласный","" ],
	[ "stimmlos werden (Konsonant)","оглушаться – оглушиться","" ],
	[ "Stoffwechsel","обмен веществ","" ],
	[ "Stollen","рождественный кекс","" ],
	[ "stolpern","спотыкаться - споткнуться","" ],
	[ "Storch","аист","" ],
	[ "störrisch, stur","упрямый","" ],
	[ "Strandtuch","пляжное полотенце","" ],
	[ "Strandurlaub","пляжный отдых","" ],
	[ "Strauch, Busch, Gebüsch","куст","" ],
	[ "strenge Kälte","лютый мороз","" ],
	[ "stressig","напряжённый","" ],
	[ "Strom","ток","" ],
	[ "Struktur\nStaatsstruktur ","устройство\nустройство государства","" ],
	[ "Strumpf","чулок, чулка","" ],
	[ "Strumpfhose","колготки","" ],
	[ "studieren","что-то учить: \nон учит русский язык\nгде-то учиться: \nон учится на экономическом факультете\nизучать: \nон изучает русский язык","" ],
	[ "Stuntman","каскадёр","" ],
	[ "stur, dickköpfig, störrisch, hartnäckig","упрямый","" ],
	[ "Sturm","буря","" ],
	[ "Substantiv\nnicht deklinierbare Substantive","имя существительное\nнесклоняемые существительные","" ],
	[ "Sülze","холодец","" ],
	[ "super!","здорово!","" ],
	[ "Superlativ","превосходная степень","" ],
	[ "surfen auf\n\nim Internet surfen","заходить - зайти на\nзайди на RusslandJournal.de\nсидеть в интернете","" ],
	[ "süß","сладко - слаще","" ],
	[ "Süßkirsche","черешня","" ],
	[ "Süßwasser","пресная вода","" ],
	[ "Tablet","планшет","" ],
	[ "tagsüber","днём\nв дневное время","" ],
	[ "Taiga","тайга","" ],
	[ "talentiert","талантливый","" ],
	[ "Tapete","обои (обоев) м.ч.","" ],
	[ "Tapferkeit, Kühnheit","храбрость","" ],
	[ "Tau","роса","" ],
	[ "taub machen, betäuben","оглушать - оглушить","" ],
	[ "Taucher-, Neoprenanzug","водолазный костюм","" ],
	[ "Tausendfüßler","сороконожка","" ],
	[ "tausendjährig","тысячелетный","" ],
	[ "Tauwetter","оттепель, -ли","" ],
	[ "Teeliebhaber","чаёвник","" ],
	[ "Teenager, Jugendlicher, Heranwachsender, Halbwüchsiger","подросток","" ],
	[ "Teerunde","чаёк\nчаепитие","" ],
	[ "Tein (Te’in)","теин","" ],
	[ "Tempel","храм","" ],
	[ "Temperaturrückgang\nTemperatursturz","понижение температуры\nпадение температуры","" ],
	[ "Teppich","ковёр, ковра","" ],
	[ "teuer","дорого - дороже","" ],
	[ "Teufel","бес\nчёрт","" ],
	[ "Theateraufführung\nEr schenkte ihm das Privileg, Theateraufführungen zu veranstalten.","содержание спектакли\nОн подарил ему привилегию на содержание спектаклей.","" ],
	[ "Thema anschneiden, vorkommen, behandeln","затрагивать – затронуть тему","" ],
	[ "Thymian","тимьян\nчабрец","" ],
	[ "tief","глубоко - глубже","" ],
	[ "Tipp, Hinweis","подсказка","" ],
	[ "Tischtennis","настольный теннис","" ],
	[ "Tochter","дочь - дочери","" ],
	[ "Todesstrafe","смертный приговор (в 1996 последний смертныи приговор в России)","" ],
	[ "Tontechniker","звукорежиссёр","" ],
	[ "Topf","горшок","" ],
	[ "Törtchen","пирожное","" ],
	[ "Toter","мертвец","" ],
	[ "trainieren, üben","тренироваться\nупряжняться","" ],
	[ "Transsibirische Eisenbahn","транссибирская магистраль","" ],
	[ "Transsibirische Eisenbahn","транссибирская магистраль","" ],
	[ "trauen, vertrauen, glauben","верить - поверить\nне верю своим глазам","" ],
	[ "Traum (im Schlaf)","сон (сни – мн. ч.)","" ],
	[ "träumen von\nich hatte einen Albtraum\nich habe geträumt, dass\nwenn du von Honig geträumt hast","сниться – присниться\nмне снился страшный сон\nмне снилось, что\nесли тебе приснился мёд","" ],
	[ "Trennung\n(eines Paares)","отрыв\nразлука","" ],
	[ "Trichter","воронка","" ],
	[ "trinken aus","пить в чём","" ],
	[ "Trinkspruch","тост","" ],
	[ "trübe, finster, mürrisch","пасмурный\nмрачный","" ],
	[ "Tschüssi","пока-пока","" ],
	[ "U-Bahn","подземка","" ],
	[ "Übelkeit","тошнота","" ],
	[ "üben, lernen","упряжняться - поупряжняться","" ],
	[ "über achtzig","за восемьдесят","" ],
	[ "Überbleibsel","пережиток","" ],
	[ "überflüssig","лишний","" ],
	[ "übergießen","заливать - залить","" ],
	[ "überprüfen\nwir überprüfen den Brückenöffnungsplan\n\nüberprüfe dein Allgemeinwissen\nüberprüfe die Wörter in einem Wörterbuch","уточнять – уточнить\nуточним график развода мостов\nпроверять – проверить\nпроверь свою эрудицию\nпроверяй слова по словарю","" ],
	[ "überqueren, überschreiten","пересекать","" ],
	[ "Ufer","берег","" ],
	[ "um eine Stunde","на один час","" ],
	[ "um Mitternacht","в полночь","" ],
	[ "Umarmung","объятие","" ],
	[ "umdrehen","перевёртывать – перевернуть\nповорачивать - повернуть","" ],
	[ "Umfang, Volumen","объём","" ],
	[ "umfangreich","объёмный","" ],
	[ "Umgangssprache\nin der Umgangssprache","разговорная речь\nв просторечии","" ],
	[ "Umleitung","объезд","" ],
	[ "Umluft (Ofen)","духовка с вентилятором","" ],
	[ "umstellen\nDie Uhren werden um 2 Uhr nachts um eine Stunde vorgestellt","переводить – перевести\nЧасы переводятся в 2 часа ночи на один час вперёд","" ],
	[ "umstritten","спорный","" ],
	[ "unakzeptabel, unannehmbar, unzulässig","неприемлемый","" ],
	[ "unantastbar","неприкосновенный","" ],
	[ "unaufhörlich","беспрестанный","" ],
	[ "unbedingt","непременно","" ],
	[ "unberührt (Natur)","нетронутый","" ],
	[ "unbeschadet","невредимый","" ],
	[ "unbetont","безударный\nбез ударения","" ],
	[ "und (aneinanderreihende Konjunktion)\nund, aber (entgegengesetzte Konjunktion; \nsondern (nach Verneinung)","и\n\nа","" ],
	[ "undeklinierbare Substantive","несклоняемые существительные","" ],
	[ "undeutlich","невнятный","" ],
	[ "unersetzlich","незаменимый\nСамовар – незаменимый помощник чаёвника","" ],
	[ "Unfug treiben","шалить несов.\nшалю, шалишь","" ],
	[ "ungefähr, etwa","лет 18 / примерно 18 лет\nминут 20 / около 20 минут\nметра два / где-то два метра\nчасам к пяти / (приблизительно) к пяти часам","" ],
	[ "ungenießbar","несъедобный","" ],
	[ "ungespritzt","неопрысканный","" ],
	[ "unglaublich, ungeheuerlich, groß","неимоверный","" ],
	[ "Unkenntlichkeit","неузнаваемость","" ],
	[ "Unsinn, du brauchst es verdammt noch mal nicht","На хрен тебе это сдалось","" ],
	[ "Untergang","закат","" ],
	[ "Untergebener, Mitarbeiter","подчинённый","" ],
	[ "unterhaltsame weltliche / mondäne Veranstaltung","развлекательное светское мероприятие","" ],
	[ "Unterhemd\nUnterhose","майка\nтрусы","" ],
	[ "Unterrichtsbeginn","начало занятий","" ],
	[ "Unterwerfer","покоритель","" ],
	[ "unvergleichlich","несравнимый","" ],
	[ "üppig","пышный","" ],
	[ "üppig, prächtig, prunkvoll, pompös; \nfluffige Masse (Teig)","пышный\n\nпышная масса","" ],
	[ "Urheberrecht","авторское право\nавторское свидетельство","" ],
	[ "Urteil","приговор","" ],
	[ "veralbern","прикалываться (ugs.)","" ],
	[ "veranstalten, organisieren","устраивать - устроить","" ],
	[ "Veranstaltung","мероприятие","" ],
	[ "verbrennen","разгораться\nДрова в печи хорошо разгоряются","" ],
	[ "verdammt schlecht (Befinden)","чертовски плохо","" ],
	[ "Verdammt\nVerdammt, es ist nicht wichtig","Блин!\nХрен с ним!","" ],
	[ "verdammt, zum Tode verurteilt","обречённый","" ],
	[ "Verdauung","пищеварение","" ],
	[ "verdünnen","разжижать – разжидить\nразжижу, -идишь, -идят","" ],
	[ "verehren, achten\nverehren, bewundern","чтить\nпочитать","" ],
	[ "Verehrer","почитатель","" ],
	[ "vereidigter Übersetzer","присяжный переводчик","" ],
	[ "Vereinte Nationen","Организации Объединённыз Наций","" ],
	[ "Vergeltung","возмездие","" ],
	[ "vergießen","проливать - пролить","" ],
	[ "Vergnügung(sevent)","развлечение","" ],
	[ "verheiratet mit","замужем за + твор. п.\nженат на + предл. п.\nОна замужем за великим князем.\nОн женат на Матильде.","" ],
	[ "verheißen, versprechen","сулить - посулить","" ],
	[ "Verkehrsmittel","средство передвижения","" ],
	[ "Verlag","издательство","" ],
	[ "verlesen, auslesen, sortieren (Früchte)","перебирать - перебрать","" ],
	[ "Verlobter","жених, -ниха","" ],
	[ "Verlobung","обручение","" ],
	[ "verlockend","заманчивый","" ],
	[ "Verlockung, Versuchung, Reiz","соблазн","" ],
	[ "Vermächtnis, Nachlass, Erbe","наследие","" ],
	[ "Vernunft","разум","" ],
	[ "verschärfen, erhärten","ужесточать - ужесточить","" ],
	[ "verschlafen","просыпать – проспать","" ],
	[ "Verschluss","замок","" ],
	[ "Versicherungsschein","страховой полис","" ],
	[ "verspielt","игривый","" ],
	[ "Verstorbener","покойник","" ],
	[ "Versuchung","искушение","" ],
	[ "Vertrag","договор","" ],
	[ "vertragen (Lebensmittel)","переносить – перенести\nони не переносят терпкий теин","" ],
	[ "verursachen\nsich zufügen, bei sich verursachen","причинять – причинить\nпричинять – причинить себе\nЯ могу причинить себе ненужный вред","" ],
	[ "verwendbar sein, brauchen können","пригодиться сов.\n\nэти странички тебе могут пригодиться","" ],
	[ "Verwöhnung","баловство","" ],
	[ "viel Erfolg","удачи","" ],
	[ "viel zu wünschen übrig lassen","оставлять желать лучшего","" ],
	[ "viele","немало","" ],
	[ "viele","немало","" ],
	[ "Vielfalt","многообразие\nразнообразие","" ],
	[ "Vielfraß","обжора","" ],
	[ "Vokabeltrainer","тренировка лексики","" ],
	[ "Vokal\nVokalausfall","гласный (звук)\nвыпадение гласных / гласной буквы","" ],
	[ "Vokaleinschub","вставка гласной буквы","" ],
	[ "Völkerverständigung","взаимопонимание между народами","" ],
	[ "Volkseinheit","народное единство","" ],
	[ "Volksfest","гулянье, -ня","" ],
	[ "Volksstamm, Gemeinschaft, Nationalität","народность","" ],
	[ "Volkstracht","национальный костюм","" ],
	[ "Vollmond","полнолуние","" ],
	[ "vom 20. Februar bis zum 20. März","с 20 февраля по 20 мáрта\nnach der Präposition с steht die Ordnungszahl im Genitiv, nach по im Akkusativ, der Monat steht in beiden Fällen im Genitiv","" ],
	[ "vom Grill","на углях","" ],
	[ "von 1993 bis 1995","с 1993 по 1995 год","" ],
	[ "von diesem Tag an, seither","с этого дня","" ],
	[ "von dort ist es nicht (mehr) weit","оттуда уже рукой подать","" ],
	[ "von Moskau nach Wladiwostok","из Москвы во В-ток","" ],
	[ "von Moskau nach Wladiwostok\nVon welchem Bahnhof fährt der Zug nach Jaroslawl ab?","из Москвы во Владивосток\nС какого вокзала идёт поезд на Ярославль?","" ],
	[ "von rechts nach links","справа налево","" ],
	[ "Vorgesetzter, Chef","начальник, шеф","" ],
	[ "Vorliebe, Geschmack","вкус","" ],
	[ "Vorrat, Reserve","запас","" ],
	[ "Vorrats-, Abstellkammer","кладовка","" ],
	[ "Vorstellungskraft, Phantasie, Einbildung","воображение","" ],
	[ "wählen (politisch)","избирать – избрать (парламент)","" ],
	[ "wahnsinnig (a. pos.), verrückt","безумный","" ],
	[ "wahre Geschichte","быль ж. (были)","" ],
	[ "wahrsagerisch, prophetisch","вещий","" ],
	[ "Wal","кит, -та","" ],
	[ "Walderdbeere","земляника","" ],
	[ "Walross","морж, -жа","" ],
	[ "Wandleuchte","бра","" ],
	[ "warum auch nicht?","почему бы и нет?","" ],
	[ "was soll ich jetzt hier?","какого хрена я сюда притащился?","" ],
	[ "Wassermelone","арбуз","" ],
	[ "Wasserreservoir","водоём","" ],
	[ "Wasserstoff","водород","" ],
	[ "wechselnd, variabel\nwechselnd / teilweise bewölkt","переменный\nпеременная облачность","" ],
	[ "wecken","будить - разбудить","" ],
	[ "wehtun, schmerzen","болеть\nон/она болит\nони болят","" ],
	[ "Weibchen","самка","" ],
	[ "weichgekochtes Ei","яйцо всмятку","" ],
	[ "Weihnachten","Рождество","" ],
	[ "Weihnachtskaktus","декабрист","" ],
	[ "Weinbau","виноделие","" ],
	[ "weit","далеко - дальше","" ],
	[ "Welche Sprachen sprichst du?","На каких языках ты говоришь?","" ],
	[ "Welches Hobby hast du?","Какое у тебя хобби?","" ],
	[ "Weltkulturerbe\n\n\n\nWeltnaturerbe","всемирное наследие\nпамятник входит с 1992 года в список объектов всемирного наследия ЮНЕСКО\nвсемирное природное наследие\nБайкал входит с 1986 года в список Всемирного природного наследия ЮНЕСКО","" ],
	[ "Weltreise","кругосветное путешествие","" ],
	[ "wenig","мало – меньше\nнемногий","" ],
	[ "wenn etwas sein sollte","если что","" ],
	[ "wenn ich mich (dir) vorstellen darf","давай я тебе представлюсь","" ],
	[ "Werk","произведение","" ],
	[ "wertvoll, wichtig","ценный","" ],
	[ "WhatsApp-Nachricht","сообщение в Ватсапе","" ],
	[ "wichtig","крупный","" ],
	[ "widerstandsfähig\nstandhaft","стойкий\nвыносливый","" ],
	[ "wie geht es dir heute?\nes geht","как у тебя сегодня дела?\nпойдёт","" ],
	[ "wie kann ich Ihnen helfen?","чем (я) могу Вам помочь?","" ],
	[ "wie kann man es allen recht machen","как угодить всем","" ],
	[ "wie schade, das ist schade","какая досада (Ärger, Entrüstung, Verdruss)","" ],
	[ "wiederverwendbar, Mehrweg-","многоразовое использование","" ],
	[ "Wiege","колыбель, -ли ж.","" ],
	[ "Wildkräuter","дикорастущая трава","" ],
	[ "Winterschlaf halten","впадать – впасть в спячку","" ],
	[ "Wirtshaus","трактир","" ],
	[ "wissbegierig","любознательный","" ],
	[ "Wissenschaftler, Forscher","научный работник\nнаучный исследователь","" ],
	[ "wissenschaftlich, Forschungs-","научный","" ],
	[ "Wodkaglas","стопка","" ],
	[ "Wohlergehen, -stand","благополучие","" ],
	[ "wohlerzogen","воспитанный","" ],
	[ "wohlwollend, gönnerhaft","доброжелательный","" ],
	[ "Wohn(sitz)adresse","адрес проживания","" ],
	[ "Wohnsituation","жилищная ситуация","" ],
	[ "wolkenlos","безоблачный","" ],
	[ "wollen wir einen Spaziergang machen?","может погуляемся?","" ],
	[ "Wörter, bei denen die Änderung der Betonung …","слова, изменение ударения в которых ...","" ],
	[ "Wortverbindung","словосочетание","" ],
	[ "Wucherpreis","обдираловка","" ],
	[ "wunderbar\n(wie) wunderbar","замечательный\nкакая прелесть","" ],
	[ "wundervoll","удивительный\nчудесный","" ],
	[ "wundheilend","ранозаживающий","" ],
	[ "Wurzelgemüse","корнеплодные овощи","" ],
	[ "Yoga","йога","" ],
	[ "Zahl","число\nцифра","" ],
	[ "Zahnarzt\nZahnarztpraxis","стоматолог\nстоматологическая клиника","" ],
	[ "zart","нежный","" ],
	[ "Zauberer, Zauberin","волшебник, волшебница","" ],
	[ "zaubern","колдовать","" ],
	[ "Zaun","забор","" ],
	[ "Zeichen","маркер","" ],
	[ "Zeichentrickfilm","мультипликационный фильм\nмультфильм","" ],
	[ "Zeitplan, Fahrplan\ngenauer, klarer Zeitplan","график\nчёткий график","" ],
	[ "Zeitrechnung","летоисчисление","" ],
	[ "Zeitvertreib","времяпрепровождение","" ],
	[ "Zeitzone","часовой пояс","" ],
	[ "Zelle (biol.)","клетка","" ],
	[ "zerkleinern, zermalmen, zerstückeln","дробить – раздробить - надробить","" ],
	[ "zerstreut","рассеянный","" ],
	[ "Zeste, Zitronenschale","цедра лимона","" ],
	[ "Zimmermann, Tischler","плотник","" ],
	[ "Zimt","корица","" ],
	[ "Zischlaut","шипящий","" ],
	[ "Zobelfell","шкура соболя","" ],
	[ "zottelig","лохматый","" ],
	[ "zu … serviert man …","к (чему) подаются (что)","" ],
	[ "zu besonderen Anlässen","по особым случаям","" ],
	[ "zu einer Vorlesung gehen","пойти на лекцию","" ],
	[ "zu Gast sein\nin verschiedenen Jahren waren … beim Festival zu Gast","становиться\nв разный годы гостями фестиваля становились ...","" ],
	[ "zubereiten","готовить - приготовить","" ],
	[ "Zubereitung (Rezept)","способ приготовления","" ],
	[ "Zucchini","кабачок","" ],
	[ "zuckersüß","сладкий как мёд","" ],
	[ "zufällig","случайный","" ],
	[ "Zufluss (Nebenfluss)\nder linksseitige Zufluss","приток\nлевый приток","" ],
	[ "Zufriedenheit","удовлетворённость","" ],
	[ "Zug, Prozession","шествие","" ],
	[ "Zugbrücke","разводный мост","" ],
	[ "zulegen, verlängern, verstärken, ansetzen","наращивать - нарастить","" ],
	[ "zum ersten Mal","впервые","" ],
	[ "zum Spazierengehen, beim Spaziergang","на прогулку","" ],
	[ "zum Unterricht gehen","идти на урок","" ],
	[ "zum Valentinstag","к Дню святого Валентина","" ],
	[ "Zungenbrecher","скороговорка","" ],
	[ "zur Hälfte, in zwei Hälften; entzwei","пополам","" ],
	[ "zurzeit","в данный момент","" ],
	[ "zusammenstürzen\nherfallen über","обрушиваться - обрушиться\nобрушиваться - обрушиться на","" ],
	[ "Zweig (kleinerer)\n(größerer)","ветка\nветвь ж., ветви","" ],
	[ "zwitschern","чирикать","" ],
	[ "базар\nбазарная баба\nбазар тебе не нужен\nбез базара\nкрутой базар\nлевый базар\nне устраивай базар\nотвечать за базар","Markt\nKlatschtante\ndu brauchst keinen Tratsch\nkeine Widerrede\ncooler / abgefahrener Tratsch\nunpassender Tratsch\nmach keinen Quatsch\n(etwas) auslöffeln, zu seinen Worten stehen","" ],
	[ "базарить / разводить базар\nраскрутить на базар","tratschen, quatschen\njdn zum Schwatzen bringen / überreden","" ],
	[ "безукоризненный","makellos, tadellos, einwandfrei","" ],
	[ "включать – включить \n\nОтель был включён в список охраняемых государством памятников истории и культуры\nРусский балет включает в себя десятка названий","einschalten, anschalten;\naufnehmen, einbeziehen\nDas Hotel wurde in die Liste der staatlich geschützten Kulturdenkmäler aufgenommen\nDas russische Ballett umfasst etwa ein Dutzend Titel","" ],
	[ "вписываться – вписаться в список\n\nэто не вписывается в правила хорошего тона","sich in die Liste eintragen \n\n(dazu)passen\ndas passt nicht zum guten Ton","" ],
	[ "вялый","schlaff\nwelk, verwelkt\nträge, faul","" ],
	[ "дисциплина","Disziplin, Fach, Teilgebiet","" ],
	[ "дробленный","zerkleinert, zerstückelt, zermalmt","" ],
	[ "ездить ","(hin und her, in unterschiedliche Richtungen)\nходить","" ],
	[ "ехать","zielgerichtet, in eine bestimmte Richtung)\nидти","" ],
	[ "жёсткий","fest, hart\nzäh\nstreng, hart","" ],
	[ "заманивать – заманить","anlocken, verlocken, hineinlocken","" ],
	[ "знатный","vornehm, angesehen, adelig","" ],
	[ "искажать – исказить (смысль)","entstellen\nverdrehen\nverzerren","" ],
	[ "коренной","grundlegend\ngebürtig, alteingesessen, indigen","" ],
	[ "корочка","Kruste, Schale","" ],
	[ "крутой\nкрутое произведение музыки разг.","fest\ncoole Musikaufführung","" ],
	[ "настойчивый\nнастойчиво тренироваться","beharrlich, eindringlich, zielstrebig","" ],
	[ "недопустимый","unzulässig","" ],
	[ "неприемлемый","inakzeptabel","" ],
	[ "образование","Bildung, Gründung, Ansatz","" ],
	[ "объявление","Ankündigung, Erklärung, Bekanntmachung, Aushang, Inserat, Anzeige","" ],
	[ "однородный","homogen, gleichartig","" ],
	[ "опрятный","ordentlich, adrett, sauber, gepflegt","" ],
	[ "оснащать – оснастить (оборудовать) чему-л. \n(снабдить)\nГостиница была оснащена по последнему слову техники","ausrüsten\n\nausstatten\nDas Hotel war (schon zu seiner Zeit) mit der neuesten Technik ausgestattet","" ],
	[ "остроумный","geistreich, witzig","" ],
	[ "осыпаться - осыпаться","abbröckeln, abfallen\nBlätter verlieren","" ],
	[ "отвар","Aufkochen, Aufguss, Sud, Brühe, Elixier","" ],
	[ "отображать – отобразить","darstellen, abbilden","" ],
	[ "оформление","Gestaltung, Dekoration;\nAbfertigung","" ],
	[ "перекрывать – перекрыть\n\n\n\nманжет перекрыл кровоток","überdachen; \nverkleiden (Bauwesen);\nversperren, abschließen, abtrennen\nDie Manschette unterbrach den Blutfluss","" ],
	[ "подмечать – подметить\n\nкрестьяне подмечали разные детали","(be)merken; kennzeichnen; notieren\ndie Bauern notierten verschiedene Details","" ],
	[ "подтягивать – подтянуть\n\n\n\nОн несколько раз переделывал хореографию подтягивая к меняющимся вкусам публики.","straff-, festziehen; \nfig. zur Erfüllung der Pflichten, zur Disziplin anhalten, erziehen;\nanpassen\nEr änderte die Choreographie mehrmals ab, um sie dem veränderten Geschmack des Publikums anzupassen.","" ],
	[ "поражать – поразить (попасть в цепь, уничтожить)\n(о болезни и т. п.)\n(удивить, ошеломить) чем-л.\nнепрятно поразить\nИнтерьеры поражали своей роскошью и великолепием","treffen, vernichten;\n\nbefallen, heimsuchen;\nüberraschen, bestürzen\njdn. unangenehm überraschen","" ],
	[ "преподносить – преподнести\n\nРодители преподносят букеты цветов","überreichen\nmitteilen, berichten","" ],
	[ "прививать - привить","beibringen, anerziehen;\npfropfen, okulieren","" ],
	[ "произносить – произнести\nони произносят поздравления","aussprechen, überbringen","" ],
	[ "протирать – протереть\n\n\nЯгоды протри через сито","ab-, durchreiben, durchschaben;\nabwischen, blankreiben;\n(durch ein Sieb) durchschlagen\nStreiche die Beeren durch ein Sieb","" ],
	[ "пушистый","flauschig, flockig","" ],
	[ "разведённый\nразведённый в холодной воде крахмал","geschieden\naufgelöst in, verrührt in","" ],
	[ "скудный","karg, mager, armselig","" ],
	[ "слагать – сложить\n\nПростой народ сгагал множество былей о море","niederlegen\nverfassen, dichten, komponieren\nDas einfache Volk erzählte viele (wahre) Geschichten über das Meer","" ],
	[ "сообразительный","aufgeweckt, findig, pfiffig","" ],
	[ "стать – право иметь отчество стали получать предприниматели","Unternehmer erhielten das Recht, einen Vatersnamen zu führen","" ],
	[ "суровый\nсуровый климат","streng, rau, hart\nraues Klima","" ],
	[ "тёртый","gerieben;\ngerissen (fig.), durchtrieben","" ],
	[ "уделять – уделить\nБольшее внимание уделяют ученикам","widmen, zuteilen, schenken","" ],
	[ "умеренный\nдопускается умеренное употребление вина","gemäßigt, maßvoll, moderat","" ],
	[ "упорный\nупорная борьба\nупорно тренироваться","hartnäckig, beharrlich, starrköpfig\nhartnäckiger Kampf\nhart trainieren","" ],
	[ "управлять – управить кем-чем-л.","lenken, leiten, verwalten, regieren (polit. und ling.)","" ],
	[ "усваивать – усвоить (воспринять, перенять)\n(выучить)\n(переработать)\nусваивать лекарство","auffassen, annehmen, aneignen\n\nerlernen, begreifen\nassimilieren, verdauen, aufnehmen\nein Arzneimittel aufnehmen, absorbieren","" ],
	[ "уставать – устать","müde werden, ermüden","" ],
	[ "хрупкий","brüchig, zerbrechlich, spröde;\nzart, schwächlich, gebrechlich","" ],
	[ "частый\n(быстрый)\n(густой)\nчастое сито","häufig\nschnell\ndicht, fein\nfeines Sieb","" ],
	[ "чебурахнуться сов. в. разг.\nя чебурахнусь\nты чебурахнешься\nмы чебурахнемся\nони чебурахнутся","hinfallen, stürzen, zusammenbrechen","" ],
	[ "чебурашка","Kullerchen, Plumps","" ],
	[ "чётый","gerade (Zahl)","" ],
	[ "щупать – пощупать пульс","Puls fühlen","" ]
]
